# https://aider.chat/docs/config/aider_conf.html

# Default Model
model: claude-sonnet-4-20250514

# AWS Settings
set-env:
  - AWS_REGION=us-east-1
  - AWS_PROFILE=default

# Recommended
# Use $AIDER_MODEL to select aliases on different computers
alias:
  - "kip:bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0"

# Behavior
cache-prompts: false
check-update: false
multiline: false
notifications: true
show-release-notes: false
stream: true
suggest-shell-commands: false
watch-files: true
yes-always: true

# Git
# Disabled because of: https://github.com/Aider-AI/aider/issues/3049
gitignore: false
auto-commits: false
dirty-commits: false

# Theme
code-theme: monokai
user-input-color: "#d7af5f"
tool-output-color: "#d0d0d0"
tool-error-color: "#ff8080"
tool-warning-color: "#afd700"
assistant-output-color: "#d0d0d0"
completion-menu-color: "#d0d0d0"
completion-menu-bg-color: "#303030"
completion-menu-current-color: "#585858"
