trailingComma = "es5"
tabWidth = 2
semi = false
singleQuote = true
htmlWhitespaceSensitivity = "ignore"
proseWrap = "preserve"

[[overrides]]
files = ".alacritty.yml"
# necessary to stay consistent with alacritty-colorscheme generated results
options = { bracketSpacing = false }
