#!/bin/bash

set -e

DIR_SEARCH="$1"
DIR_ORIGINAL="$2"
DIR_REPLACE="$3"

if [ $# -ne 3 ]; then
  echo "did not provide 3 arguments"
  echo "update.sh dir_search dir_original dir_replace"
  exit 1
fi

for FILE in `find "$DIR_SEARCH" -type l 2>&1 | grep -v "Permission denied"`; do
  LINK=$(readlink $FILE)
  if [[ "$LINK" == $DIR_ORIGINAL* ]]; then
    NEW_LINK=$(echo "$LINK" | sed "s#$DIR_ORIGINAL#$DIR_REPLACE#1")
    echo "ln -s $NEW_LINK $FILE"
    rm "$FILE"
    ln -s "$NEW_LINK" "$FILE"
  fi
done
