# :schema https://raw.githubusercontent.com/rvben/rumdl/refs/heads/main/rumdl.schema.json

disable = ["MD013", "MD033", "MD036", "MD046", "MD059"]
flavor = "mkdocs"

[MD007]
indent = 4

[MD046]
style = "fenced"
