live_config_reload = false

[colors]
draw_bold_text_with_bright_colors = true
primary = {background = "#0A0E14", foreground = "#B3B1AD"}

[colors.bright]
black = "#686868"
red = "#F07178"
green = "#C2D94C"
yellow = "#FFB454"
blue = "#59C2FF"
magenta = "#FFEE99"
cyan = "#95E6CB"
white = "#FFFFFF"

[colors.normal]
black = "#01060E"
red = "#EA6C73"
green = "#91B362"
yellow = "#F9AF4F"
blue = "#53BDFA"
magenta = "#FAE994"
cyan = "#90E1C6"
white = "#C7C7C7"

[cursor.style]
blinking = "Never"

[env]
TERM = "tmux-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0
normal = {family = "Fira Mono Nerd Font Mono", style = "Medium"}

[keyboard]
bindings = [
  {key = "F11", action = "ToggleFullscreen"},
  {key = "LBracket", mods = "Control", mode = "Vi", action = "ClearSelection"},
  {key = "Q", mode = "Vi", action = "ScrollToBottom"},
  {key = "Q", mode = "Vi", action = "ToggleViMode"},
  {key = "Space", mods = "Shift|Control", action = "None"},
  {key = 5, mods = "Shift", mode = "Vi", action = "Last"},
  {key = 6, mods = "Shift", mode = "Vi", action = "Bracket"},
  {key = 11, mods = "Shift", mode = "Vi", action = "FirstOccupied"}
]

[shell]
program = "/home/sroeca/config/bin/entrypoint-alacritty-tmux"

[window]
title = "Chez La Couve"
dynamic_title = false
dynamic_padding = true
decorations_theme_variant = "Dark"
padding = {x = 2, y = 2}
