# :schema https://raw.githubusercontent.com/distinction-dev/alacritty-schema/refs/heads/main/alacritty/reference.json

[cursor.style]
blinking = "Never"

[env]
TERM = "tmux-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0
normal = {family = "Fira Mono Nerd Font Mono", style = "Medium"}

[general]
import = ["~/.cache/alacritty/background.toml"]
live_config_reload = true

[terminal.shell]
program = "/home/sroeca/config/bin/entrypoint-alacritty-tmux"

[window]
dynamic_title = false
dynamic_padding = true
padding = {x = 2, y = 2}
