local M = {}

-- Keep this list curated: every entry is applied automatically, not suggested,
-- so a typo variant must never be a correctly spelled word.
-- Keys are correct spellings and values are their typo variants. Every key uses
-- the same syntax so the declarations can be sorted lexicographically.
-- Brace alternatives are paired by position. An empty pair on the correct side
-- copies the typo suffixes, so ["separate{}"] = "seperate{,ly}" expands to
-- seperate -> separate and seperately -> separately.
-- Multiple pairs form a product, so ["s{ome}{}"] =
-- "{smoe,soem}{,body}" also covers smoe, soem, smoebody, and soembody.
local corrections = {
  ["abandonment"] = "abandonnment",
  ["abbreviation{}"] = "abreviation{,s}",
  ["ability"] = "abiltiy",
  ["about"] = "{abotu,baout}",
  ["above"] = "abvoe",
  ["absence{}"] = "absense{,s}",
  ["absolutely"] = "absolutley",
  ["absorption"] = "{aborption,absoprtion,absorbtion}",
  ["abstinence"] = "abstenance",
  ["abstract{}"] = "abstact{,s,ed,ing,ion,ions}",
  ["abstrac{}"] = "abtrac{t,ts,ted,ting,tion,tions}",
  ["abundance{}"] = "abundence{,s}",
  ["abundant"] = "abundent",
  ["abysmal{}"] = "abismal{,ly}",
  ["academic"] = "acadmic",
  ["academy"] = "acadamy",
  ["accelerat{}"] = "acelerat{e,es,ed,ing,ion,ions}",
  ["accelera{}"] = "accellera{te,tes,ted,ting,tion,tions}",
  ["accept"] = "acecpt",
  ["accepta{}"] = "accepti{ble,bly}",
  ["accessor{}"] = "acessor{y,ies}",
  ["access{}"] = "acess{ible,ibly,ibility}",
  ["accidentally"] = "{accidentaly,accidently}",
  ["accommodat{}"] = "accomodat{e,es,ed,ing,ion,ions}",
  ["accommoda{}"] = "acommoda{te,tes,ted,ting,tion,tions}",
  ["accompan{}"] = "accompon{y,ies,ied,ying}",
  ["accomplish{}"] = "acomplish{,es,ed,ing,ment,ments}",
  ["accompli{sh}{}"] = "accompli{s}{,ed,ing,ment,ments}",
  ["according"] = "acording",
  ["accountabilit{}"] = "accountabilt{y,ies}",
  ["accreditation"] = "{accrediation,accredidation}",
  ["accuracy"] = "accuracey",
  ["accurat{}"] = "acurat{e,ely}",
  ["accustomed"] = "accostumed",
  ["achiev{}"] = "acheiv{e,es,ed,ing,ement,ements}",
  ["achie{}"] = "ache{ve,ves,ved,ving,vement,vements}",
  ["acknowledg{}"] = "acknowleg{e,es,ed,ing,ement,ements}",
  ["acoustic"] = "{accoustic,acousitc}",
  ["acquiesc{e,es,ed,ing}"] = "acquiess{,es,ed,ing}",
  ["acquir{}"] = "aquir{e,es,ed,ing}",
  ["acquisition"] = "aquisition",
  ["acqui{}"] = "acqu{re,res,red,ring}",
  ["acreage{}"] = "acerage{,s}",
  ["acronym{}"] = "acornym{,s}",
  ["across"] = "accross",
  ["action"] = "atcion",
  ["activate"] = "activte",
  ["activit{}"] = "activt{y,ies}",
  ["actually"] = "actualy",
  ["actual{}"] = "acutal{,ly}",
  ["adapt{}"] = "adpat{,s,ed,ing,ation,ations,ive}",
  ["ada{}"] = "adda{pt,pts,pted,pting,ptation,ptations,ptive}",
  ["additional"] = "additonal",
  ["addition{}"] = "additon{,s}",
  ["address{}"] = "adress{,es,ed,ing}",
  ["adequate"] = "adequete",
  ["adjacent"] = "adjecent",
  ["adjective"] = "adjative",
  ["adjust{}"] = "adjsut{,s,ed,ing,ment,ments}",
  ["adjus{}"] = "adus{t,ts,ted,ting,tment,tments}",
  ["administrator"] = "adminstrator",
  ["administrat{}"] = "adminstrat{ion,ions,ive}",
  ["admissible"] = "{admisible,admissable}",
  ["admission{}"] = "admision{,s}",
  ["adolescence"] = "adolesence",
  ["adolescent{}"] = "adolecent{,s}",
  ["advanced"] = "advnaced",
  ["advantage"] = "advatnage",
  ["advertisement"] = "advertisment",
  ["advertising"] = "advertisin",
  ["advice"] = "adivce",
  ["advisable"] = "adviseable",
  ["aerial{}"] = "aeriel{,s}",
  ["aesthetic{}"] = "asthetic{,s}",
  ["affiliat{}"] = "affilat{e,es,ed,ing,ion,ions}",
  ["affordable"] = "affortable",
  ["after"] = "afetr",
  ["again"] = "agian",
  ["against"] = "agianst",
  ["aggregat{}"] = "agregat{e,es,ed,ing,ion,ions}",
  ["aggrega{}"] = "aggraga{te,tes,ted,ting,tion,tions}",
  ["aggressive{}"] = "agressive{,ly,ness}",
  ["agreement{}"] = "agreemnt{,s}",
  ["agriculture"] = "agricuture",
  ["alcohol"] = "alcohal",
  ["alcohol{}"] = "alchohol{,ic,ics}",
  ["algorithm{}"] = "algorithim{,s}",
  ["align{}"] = "allign{,s,ed,ing,ment,ments}",
  ["allegiance"] = "allegience",
  ["alleviat{}"] = "aleviat{e,es,ed,ing}",
  ["alliance{}"] = "aliance{,s}",
  ["allocat{}"] = "alocat{e,es,ed,ing,ion,ions}",
  ["allotted"] = "alloted",
  ["allow{}"] = "alow{,s,ed,ing,ance,ances}",
  ["along"] = "alnog",
  ["alphabetic"] = "alpahbetic",
  ["already"] = "aleady",
  ["also"] = "aslo",
  ["although"] = "althought",
  ["always"] = "alwasy",
  ["al{ign,igns,igned,igning,ignment,ignments}"] = "al{gin,gins,gined,gining,ginment,ginments}",
  ["amateur"] = "amature",
  ["amendment{}"] = "ammendment{,s}",
  ["ammunition"] = "amunition",
  ["among"] = "amoung",
  ["amount"] = "ammount",
  ["analysis"] = "analisis",
  ["analytically"] = "analyticly",
  ["annihilat{}"] = "anihilat{e,es,ed,ing,ion,ions}",
  ["anniversaries"] = "{aniversaries,aniversays,aniversarys}",
  ["anniversary"] = "{aniversay,aniversary}",
  ["announcement{}"] = "announcment{,s}",
  ["annual"] = "anual",
  ["anomal{}"] = "anomol{y,ies}",
  ["anonymous{}"] = "anonymus{,ly}",
  ["another"] = "anohter",
  ["answer"] = "anwser",
  ["anticipat{}"] = "anticiapt{e,es,ed,ing,ion,ions}",
  ["anybody"] = "{anybdoy,anybdy}",
  ["anyhow"] = "anyhwo",
  ["anyone"] = "anyoen",
  ["anyplace"] = "anypalce",
  ["anything"] = "{anyhting,anythign,anyting}",
  ["anytime"] = "anytmie",
  ["anyway"] = "anyawy",
  ["anywhere"] = "anyhwere",
  ["apocalyp{}"] = "acopalyp{se,tic}",
  ["apolog{}"] = "appolog{y,ies}",
  ["apparatus"] = "aparatus",
  ["appearance{}"] = "appearence{,s}",
  ["appendix"] = "apendix",
  ["applicable"] = "aplicable",
  ["application{}"] = "applicaiton{,s}",
  ["appreciat{}"] = "apreciat{e,es,ed,ing,ion,ions}",
  ["apprecia{}"] = "appricia{te,tes,ted,ting,tion,tions}",
  ["appropriate{}"] = "appropiate{,ly}",
  ["approximately"] = "aproximatly",
  ["ap{parent}{}"] = "ap{arent,parant}{,ly}",
  ["arbitrary"] = "arbitary",
  ["architecture{}"] = "architechture{,s}",
  ["argument{}"] = "arguement{,s}",
  ["argumen{}"] = "arugmen{t,ts}",
  ["arithmetic"] = "arithmatic",
  ["around"] = "aroudn",
  ["arrangement{}"] = "arrangment{,s}",
  ["article{}"] = "artilce{,s}",
  ["assassination{}"] = "assasination{,s}",
  ["assessment{}"] = "assesment{,s}",
  ["assignment{}"] = "assigment{,s}",
  ["assistance"] = "assitance",
  ["assistant{}"] = "assitant{,s}",
  ["association{}"] = "assocation{,s}",
  ["assumption{}"] = "asumption{,s}",
  ["asymmetr{}"] = "asymetr{y,ic}",
  ["asynchronous"] = "asyncronous",
  ["atheist{}"] = "athiest{,s}",
  ["athlet{}"] = "athelet{ic,ics,ically}",
  ["atomic"] = "atmoic",
  ["attachment{}"] = "attatchment{,s}",
  ["attendance{}"] = "attendence{,s}",
  ["attention{}"] = "attension{,s}",
  ["attribut{}"] = "attrubut{e,es,ed,ing}",
  ["audience{}"] = "audiance{,s}",
  ["authentication"] = "authenication",
  ["author"] = "auhtor",
  ["authoritative"] = "authorative",
  ["authorization{}"] = "authorizaton{,s}",
  ["auxiliary"] = "auxillary",
  ["availability"] = "availablity",
  ["available"] = "{avaliable,availble}",
  ["awesome"] = "aweosme",
  ["a{cquaintance}{}"] = "a{cquaintence,quaintance}{,s}",
  ["bachelor{}"] = "bachler{,s}",
  ["back"] = "bakc",
  ["background{}"] = "backgroud{,s}",
  ["balloon{}"] = "baloon{,s}",
  ["bankruptc{}"] = "bankrupc{y,ies}",
  ["basically"] = "basicly",
  ["basic{}"] = "basci{,ally}",
  ["batter{}"] = "bater{y,ies}",
  ["beautiful"] = "beautifull",
  ["beautiful{}"] = "beutiful{,ly}",
  ["because"] = "becuase",
  ["become"] = "becmoe",
  ["before"] = "beofre",
  ["beginner{}"] = "beginer{,s}",
  ["beg{inning}{}"] = "beg{gining,ining}{,s}",
  ["behavior{}"] = "beahvior{,s}",
  ["being"] = "{beign,bieng}",
  ["believable"] = "beliveable",
  ["believ{e,es,ed,ing}"] = "bleiev{,s,ed,ing}",
  ["believ{}"] = "beleiv{e,es,ed,ing}",
  ["belie{}"] = "beli{ve,ving}",
  ["beneficial{}"] = "benificial{,ly}",
  ["benefit{}"] = "benifit{,s,ed,ing}",
  ["bene{fit,fits,fited,fiting}"] = "bene{tif,tifs,tifed,tifing}",
  ["better"] = "betetr",
  ["between"] = "betwen",
  ["bizarre{}"] = "bizzare{,ly}",
  ["boolean{}"] = "boolen{,s}",
  ["both"] = "btoh",
  ["boundar{}"] = "boundr{y,ies}",
  ["branch{}"] = "brnach{,es}",
  ["breakthrough{}"] = "breakthough{,s}",
  ["brief{}"] = "breif{,s,ly}",
  ["bring{}"] = "birng{,s,ing}",
  ["broccoli"] = "brocoli",
  ["buff{}"] = "buf{er,ers,ered,ering}",
  ["build{}"] = "biuld{,s,ing,er,ers}",
  ["buoyancy"] = "bouyancy",
  ["bureaucracy"] = "bureacracy",
  ["bureaucrat{}"] = "bureacrat{ic,ically}",
  ["b{usiness}{}"] = "{buisness,bussiness}{,es}",
  ["cacheable"] = "cachable",
  ["cach{}"] = "cahc{e,es,ed,ing}",
  ["calculat{}"] = "calcualt{ion,ions}",
  ["calendar{}"] = "calandar{,s}",
  ["calibration{}"] = "callibration{,s}",
  ["callback{}"] = "calback{,s}",
  ["called"] = "caleld",
  ["camouflag{}"] = "camoflag{e,es,ed,ing}",
  ["candidate{}"] = "canidate{,s}",
  ["canonical"] = "cannonical",
  ["capabilit{}"] = "capabilt{y,ies}",
  ["capacit{}"] = "capcit{y,ies}",
  ["caribbean"] = "carribean",
  ["catastroph{e,es}"] = "catastrof{y,ies}",
  ["categor{}"] = "catagor{y,ies}",
  ["cause"] = "casue",
  ["cautious{}"] = "causious{,ly}",
  ["ceiling{}"] = "cieling{,s}",
  ["cemetery"] = "cemetary",
  ["center"] = "cetner",
  ["certain"] = "certian",
  ["certificate{}"] = "certifcate{,s}",
  ["challeng{}"] = "chaleng{e,es,ed,ing}",
  ["challen{}"] = "challan{ge,ges,ged,ging}",
  ["changeable"] = "changable",
  ["chang{}"] = "chnag{e,es,ed,ing}",
  ["characteristic{}"] = "charateristic{,s}",
  ["character{}"] = "charactor{,s}",
  ["chassis"] = "chassy",
  ["cha{nge,nges,nged,nging}"] = "cha{gne,gnes,gned,gning}",
  ["check{}"] = "cehck{,s,ed,ing}",
  ["children"] = "chidlren",
  ["choice"] = "chioce",
  ["choose"] = "chosse",
  ["chronological"] = "cronological",
  ["circuit{}"] = "circut{,s}",
  ["circumstance{}"] = "circumstnce{,s}",
  ["clear{}"] = "claer{,s,ed,ing}",
  ["clos{}"] = "clso{e,es,ed,ing}",
  ["cod{}"] = "cdo{e,es,ed,ing}",
  ["coefficient{}"] = "coeficient{,s}",
  ["cohere{}"] = "cohera{nt,ntly}",
  ["collaboration{}"] = "colaboration{,s}",
  ["collaborative"] = "collaberative",
  ["colleague{}"] = "collegue{,s}",
  ["collection{}"] = "colection{,s}",
  ["column{}"] = "colum{,s}",
  ["combination{}"] = "combinaton{,s}",
  ["coming"] = "comming",
  ["command{}"] = "comand{,s,ed,ing}",
  ["comman{}"] = "commna{d,ds,ded,ding}",
  ["comma{nd,nds,nded,nding}"] = "coma{mnd,mnds,mnded,mnding}",
  ["commemorat{}"] = "commemmorat{e,es,ed,ing,ion,ions}",
  ["commercial{}"] = "comercial{,s}",
  ["commission{}"] = "comission{,s,ed,ing}",
  ["commis{}"] = "commi{sion,sions,sioned,sioning}",
  ["commitment{}"] = "comitment{,s}",
  ["committee"] = "comittee",
  ["committ{}"] = "commit{ed,ing}",
  ["common"] = "comon",
  ["communication{}"] = "communciation{,s}",
  ["communit{}"] = "comunit{y,ies}",
  ["comparative{}"] = "comparitive{,s,ly}",
  ["comparison"] = "comparision",
  ["compatibilit{}"] = "compatabilit{y,ies}",
  ["competition{}"] = "competion{,s}",
  ["completely"] = "completly",
  ["complet{}"] = "comlpet{e,es,ed,ing}",
  ["complexit{}"] = "compexit{y,ies}",
  ["comple{}"] = "compele{te,tes,ted,ting}",
  ["component{}"] = "componet{,s}",
  ["componen{}"] = "compnoen{t,ts}",
  ["composability"] = "composablity",
  ["composable"] = "compsable",
  ["comprehensive"] = "comphrehensive",
  ["computation{}"] = "computaton{,s}",
  ["concatenat{}"] = "concantenat{e,ed,ing,ion}",
  ["conced{e,es,ed,ing}"] = "conceed{,s,ed,ing}",
  ["conceiv{}"] = "conciev{e,es,ed,ing,able,ably}",
  ["conclusion{}"] = "conclussion{,s}",
  ["concurrency"] = "cocurrency",
  ["concurrenc{}"] = "concurenc{y,ies}",
  ["concurrent{}"] = "concurent{,ly}",
  ["conditional{}"] = "conditonal{,ly}",
  ["condition{}"] = "conditon{,s,ed,ing}",
  ["conditio{}"] = "coditio{n,ns,ned,ning}",
  ["confidence"] = "confidance",
  ["configuration{}"] = "configuraiton{,s}",
  ["configuratio{}"] = "configruatio{n,ns}",
  ["confirmation{}"] = "confirmaton{,s}",
  ["congratulations"] = "congradulations",
  ["connection{}"] = "conection{,s}",
  ["connectio{}"] = "conenctio{n,ns}",
  ["connectivity"] = "conectivity",
  ["connoisseur{}"] = "conoisseur{,s}",
  ["conscience{}"] = "conchance{,s}",
  ["conscientious{}"] = "concientious{,ly}",
  ["conscious{}"] = "concious{,ly}",
  ["consecutive{}"] = "consective{,ly}",
  ["consensus{}"] = "concensus{,es}",
  ["consequence{}"] = "consequnce{,s}",
  ["considerable"] = "considerible",
  ["consider{}"] = "consdier{,s,ed,ing,ation,ations}",
  ["conside{}"] = "concide{r,rs,red,ring,ration,rations}",
  ["consistency"] = "consistancy",
  ["consistent{}"] = "consistant{,ly}",
  ["constitutional{}"] = "consitutional{,ly}",
  ["constraint{}"] = "contraint{,s}",
  ["consumption"] = "consumtion",
  ["contain{}"] = "contian{,s,ed,ing,er,ers,ment}",
  ["contemporar{}"] = "contamporar{y,ies}",
  ["content{}"] = "contnet{,s}",
  ["continuous{}"] = "continous{,ly}",
  ["continu{}"] = "continut{e,es,ed,ing,ation,ations}",
  ["contin{}"] = "conti{ue,ues,ued,uing,uation,uations}",
  ["control"] = "cotnrol",
  ["controll{}"] = "control{ed,er,ers,ing}",
  ["controvers{}"] = "controverc{y,ies}",
  ["convenience{}"] = "convience{,s}",
  ["convenient{}"] = "convient{,ly}",
  ["conversion{}"] = "converison{,s}",
  ["convert"] = "conevrt",
  ["coordinat{}"] = "coordiant{e,es,ed,ing}",
  ["copyright{}"] = "copyrigth{,s}",
  ["correct{}"] = "corerct{,s,ed,ing,ion,ions,ly}",
  ["correc{}"] = "corec{t,ts,ted,ting,tion,tions,tly}",
  ["correlation{}"] = "corelation{,s}",
  ["correspondence{}"] = "correspondance{,s}",
  ["corresponding"] = "coresponding",
  ["could"] = "coudl",
  ["counterfeit{}"] = "counterfit{,s,ed,ing,er,ers}",
  ["courageous{}"] = "couragous{,ly}",
  ["courteous{}"] = "curteus{,ly}",
  ["co{ntext}{}"] = "co{netxt,tnext}{,s}",
  ["creat{}"] = "craet{e,es,ed,ing,or,ors}",
  ["credential{}"] = "credentail{,s}",
  ["criteria"] = "critera",
  ["criterion"] = "criteron",
  ["criticism{}"] = "critisism{,s}",
  ["crucial"] = "cruical",
  ["curious{}"] = "curius{,ly}",
  ["current{}"] = "currnet{,ly}",
  ["curriculum"] = "ciriculum",
  ["database{}"] = "datbase{,s}",
  ["daughter"] = "daugther",
  ["deallocat{}"] = "dealocat{e,es,ed,ing,ion,ions}",
  ["deceiv{}"] = "deciev{e,es,ed,ing}",
  ["decision{}"] = "descision{,s}",
  ["decisio{}"] = "deciso{n,ns}",
  ["declaration{}"] = "decleration{,s}",
  ["decommission{}"] = "decomission{,s,ed,ing}",
  ["default{}"] = "defualt{,s,ed,ing}",
  ["deferr{}"] = "defer{ed,ing}",
  ["definitely"] = "definetely",
  ["definite{}"] = "definate{,ly}",
  ["definition{}"] = "defintion{,s}",
  ["defin{e,es,ed,ing}"] = "defien{,s,ed,ing}",
  ["delete"] = "delte",
  ["delimiter{}"] = "delimeter{,s}",
  ["delimite{}"] = "delimte{r,rs}",
  ["demonstrat{}"] = "demonstat{e,es,ed,ing,ion,ions}",
  ["demon{}"] = "demo{strate,strates,strated,strating,stration,strations}",
  ["dependencies"] = "{depednencies,dependnecies}",
  ["dependency"] = "{depednency,dependnecy}",
  ["deprecat{}"] = "depreceat{e,es,ed,ing,ion,ions}",
  ["descendant{}"] = "decendant{,s}",
  ["descendan{}"] = "descenda{t,ts}",
  ["desiccated"] = "dessicated",
  ["designed"] = "desigend",
  ["desperate{}"] = "desparate{,ly}",
  ["destination{}"] = "destinaton{,s}",
  ["destroy{}"] = "destory{,s,ed,ing,er,ers}",
  ["destro{}"] = "desto{y,ys,yed,ying,yer,yers}",
  ["destruction{}"] = "destructon{,s}",
  ["detail{}"] = "detial{,s}",
  ["detai{}"] = "deta{l,ls}",
  ["determine"] = "detemrine",
  ["deterministic"] = "deteministic",
  ["development{}"] = "developement{,s}",
  ["developmen{}"] = "devlopmen{t,ts}",
  ["develop{}"] = "devlop{ed,er,ers,ing}",
  ["devel{}"] = "deve{oped,oper,opers,oping}",
  ["device{}"] = "deivce{,s}",
  ["devi{}"] = "dev{ce,ces}",
  ["diagnostic{}"] = "diagnotic{,s}",
  ["diagnosti{}"] = "diagnosi{c,cs}",
  ["dictionar{}"] = "dictionair{y,ies}",
  ["difference{}"] = "diffrence{,s}",
  ["differenc{}"] = "diferenc{e,es}",
  ["differential{}"] = "diffrential{,s}",
  ["difficult"] = "difficutl",
  ["difficul{}"] = "dificul{t,ty,ties}",
  ["dif{ferent}{}"] = "dif{erent,ferant,frent}{,ly}",
  ["dilemma{}"] = "dilema{,s}",
  ["dimensional"] = "dimentional",
  ["dimension{}"] = "dimention{,s}",
  ["diphthong{}"] = "dipthong{,s}",
  ["direct"] = "driect",
  ["direction{}"] = "directon{,s}",
  ["directio{}"] = "direcito{n,ns}",
  ["directories"] = "{direcotries,driectories}",
  ["directory"] = "{direcotry,driectory}",
  ["disabilit{}"] = "disabilt{y,ies}",
  ["disappear{}"] = "dissapear{,s,ed,ing,ance,ances}",
  ["disappea{}"] = "disapea{r,rs,red,ring,rance,rances}",
  ["disappointed"] = "dissapointed",
  ["disastrous{}"] = "disasterous{,ly}",
  ["disciplin{}"] = "disiplin{e,es,ed,ing}",
  ["discrepanc{}"] = "discrepenc{y,ies}",
  ["discretion{}"] = "discression{,s}",
  ["discussion{}"] = "discusion{,s}",
  ["discussio{}"] = "disscussio{n,ns}",
  ["display{}"] = "dispaly{,s,ed,ing}",
  ["dissatisfied"] = "disatisfied",
  ["distributed"] = "distribued",
  ["distribution{}"] = "distrubution{,s}",
  ["distribut{}"] = "distrubut{e,es,ed,ing}",
  ["distribu{}"] = "distrbu{te,tes,ted,ting,tion,tions}",
  ["dis{play,plays,played,playing}"] = "dis{lpay,lpays,lpayed,lpaying}",
  ["divisible"] = "divisable",
  ["documentation"] = "documention",
  ["does"] = "deos",
  ["drunkenness"] = "drunkeness",
  ["dumbbell{}"] = "dumbell{,s}",
  ["duplicat{}"] = "duplciat{e,es,ed,ing}",
  ["during"] = "duirng",
  ["dynamic"] = "{dyanmic,dynmaic}",
  ["d{escription}{}"] = "{desciption,descripton}{,s}",
  ["each"] = "eahc",
  ["ecclesiastical{}"] = "eclesiastical{,ly}",
  ["ecstasy"] = "{ecstacy,exstacy}",
  ["effect"] = "effcet",
  ["efficiency"] = "efficency",
  ["efficient"] = "efficent",
  ["efficiently"] = "efficently",
  ["efficient{}"] = "effecient{,ly}",
  ["eighth"] = "eigth",
  ["either"] = "{eitehr,etiher}",
  ["elegant{}"] = "elagant{,ly}",
  ["eligibility"] = "eligiblity",
  ["eligible"] = "eligable",
  ["elig{ible,ibility}"] = "elig{ble,bility}",
  ["elimination{}"] = "elemination{,s}",
  ["eliminat{}"] = "elimiat{e,es,ed,ing}",
  ["elimina{}"] = "elemina{te,tes,ted,ting}",
  ["elimi{}"] = "elim{nate,nates,nated,nating}",
  ["else"] = "esle",
  ["email"] = "emial",
  ["embarrass{}"] = "embarass{,es,ed,ing,ment}",
  ["embarras{}"] = "embarra{s,ses,sed,sing,sment}",
  ["embedd{}"] = "embed{ed,ing}",
  ["emergency"] = "emergancy",
  ["emphasize"] = "empasize",
  ["enabled"] = "enabeld",
  ["encapsulation"] = "encapuslation",
  ["encoding"] = "enconding",
  ["encyclopedia{}"] = "encylopedia{,s}",
  ["engineer{}"] = "enginer{,s,ed,ing}",
  ["enginee{}"] = "engenee{r,rs,red,ring}",
  ["enough"] = "enouhg",
  ["ensure"] = "esnure",
  ["enthusiasm"] = "enthusiam",
  ["entirely"] = "entierly",
  ["entrepreneur{}"] = "entrepeneur{,s}",
  ["entrepreneu{}"] = "entrapeneu{r,rs}",
  ["enumeration{}"] = "enumaration{,s}",
  ["enumeratio{}"] = "enumatio{n,ns}",
  ["environment{}"] = "enviroment{al,alist,alists}",
  ["env{ironment}{}"] = "env{ironemnt,iornment,iroment,rionment}{,s}",
  ["equilibrium"] = "equlibrium",
  ["equipment"] = "equiptment",
  ["equivalent{}"] = "equivilent{,s}",
  ["error"] = "erorr",
  ["especially"] = "especialy",
  ["essential"] = "essentail",
  ["essential{}"] = "esential{,ly}",
  ["evaluate"] = "evalute",
  ["evaluation{}"] = "evalutation{,s}",
  ["evaluatio{}"] = "evaulatio{n,ns}",
  ["everybody"] = "{everybdoy,everybdy}",
  ["everyday"] = "{everday,everydy}",
  ["everyone"] = "everyoen",
  ["everything"] = "{everyhting,everythign,everyting,everthing}",
  ["everywhere"] = "everyhwere",
  ["exaggerat{}"] = "exagerat{e,es,ed,ing,ion,ions}",
  ["example"] = "exmaple",
  ["exceed"] = "excede",
  ["excellence"] = "excellance",
  ["excellent"] = "excelent",
  ["exception"] = "exeption",
  ["exceptional"] = "exeptional",
  ["executable"] = "excutable",
  ["execution{}"] = "excution{,s}",
  ["exercise"] = "excercise",
  ["exhaustive"] = "exaustive",
  ["exhilarat{}"] = "exhilerat{e,es,ed,ing,ion}",
  ["existence{}"] = "existance{,s}",
  ["existenc{}"] = "exsistenc{e,es}",
  ["existing"] = "exisitng",
  ["expect"] = "exepct",
  ["experience"] = "experiance",
  ["explanation"] = "explaination",
  ["explicitly"] = "explicitlly",
  ["explicit{}"] = "explict{,ly}",
  ["explici{}"] = "expilci{t,tly}",
  ["extraordinary"] = "{extrodinary,extrordinary}",
  ["extremely"] = "extremly",
  ["e{very}{}"] = "{evey,evrey}{,body,day,one,thing,where}",
  ["facilitat{}"] = "faciliat{e,es,ed,ing}",
  ["fahrenheit"] = "farenheit",
  ["familiarity"] = "familarity",
  ["familiar{}"] = "familar{,ly}",
  ["familia{}"] = "fimilia{r,rly}",
  ["fascinating"] = "facinating",
  ["fascination{}"] = "facination{,s}",
  ["feas{ible,ibly,ibility}"] = "feas{able,ably,ability}",
  ["feature"] = "fetaure",
  ["february"] = "febuary",
  ["feedback"] = "feedbakc",
  ["fictitious"] = "ficticious",
  ["field"] = "feild",
  ["filename{}"] = "filname{,s}",
  ["filesystem{}"] = "filesytem{,s}",
  ["file{name,names}"] = "file{nmae,nmaes}",
  ["finally"] = "finaly",
  ["final{}"] = "fianl{,ly}",
  ["financial{}"] = "finacial{,ly}",
  ["find"] = "fnid",
  ["first"] = "frist",
  ["fluorescent"] = "{fluoroscent,fluroescent}",
  ["following"] = "folowing",
  ["forcibly"] = "forcably",
  ["foreign{}"] = "foriegn{,er,ers}",
  ["foreseeable"] = "forseeable",
  ["fore{ign,igner,igners}"] = "fore{gin,giner,giners}",
  ["forfeit{}"] = "forefit{,s,ed,ing}",
  ["format"] = "fomrat",
  ["formerly"] = "formely",
  ["forty"] = "fourty",
  ["forward"] = "foward",
  ["found"] = "foudn",
  ["foundation{}"] = "fundation{,s}",
  ["fourth"] = "fouth",
  ["frequenc{}"] = "frequnc{y,ies}",
  ["frequently"] = "frequenly",
  ["freque{}"] = "freqe{ncy,ncies,ntly}",
  ["friend"] = "freind",
  ["fuchsia"] = "fuschia",
  ["fulfill{}"] = "fullfill{,s,ed,ing,ment,ments}",
  ["fulfil{}"] = "fufil{l,ls,led,ling,lment,lments}",
  ["functionalit{}"] = "functionallit{y,ies}",
  ["fundamental"] = "fundemental",
  ["future"] = "futuer",
  ["fu{nction}{}"] = "fu{cntion,ntion}{,s,ing,al,ality,alities}",
  ["gauge"] = "guage",
  ["genealog{}"] = "geneolog{y,ies}",
  ["generally"] = "generaly",
  ["general{}"] = "genral{,ly}",
  ["genera{}"] = "genrea{l,lly}",
  ["genius"] = "genious",
  ["genuine"] = "genuin",
  ["given"] = "gievn",
  ["global"] = "gloabl",
  ["governmental"] = "govermental",
  ["government{}"] = "goverment{,s}",
  ["governmen{}"] = "govenmen{t,ts}",
  ["governor{}"] = "govenor{,s}",
  ["grammar"] = "grammer",
  ["grammatical{}"] = "gramatical{,ly}",
  ["grateful{}"] = "greatful{,ly,ness}",
  ["great"] = "graet",
  ["grievance{}"] = "greivance{,s}",
  ["group"] = "gruop",
  ["guarante{}"] = "gaurante{e,es,ed,eing}",
  ["guard"] = "gaurd",
  ["guidance"] = "guidence",
  ["g{uarantee}{}"] = "g{arantee,uarentee}{,s,d,ing}",
  ["handful{}"] = "handfull{,s}",
  ["handkerchief{}"] = "hankerchief{,s}",
  ["handle"] = "hanlde",
  ["happened"] = "happend",
  ["happen{}"] = "hapen{,s,ed,ing}",
  ["happe{n}{}"] = "happ{ne}{,s,ed,ing}",
  ["harass{}"] = "harrass{,es,ed,ing,ment}",
  ["have"] = "{ahve,haev,hvae}",
  ["height"] = "heigth",
  ["help"] = "hepl",
  ["helpful"] = "helpfull",
  ["heterogeneous"] = "hetrogeneous",
  ["hierarch{}"] = "heirarch{y,ies,ical,ically}",
  ["hiera{rch}{}"] = "hiera{ch}{y,ies,ical,ically}",
  ["history"] = "histroy",
  ["homogeneous"] = "homogenious",
  ["horizontal{}"] = "horizonal{,ly}",
  ["however"] = "howveer",
  ["humorous{}"] = "humurous{,ly}",
  ["hygiene"] = "hygeine",
  ["hypocris{}"] = "hipocris{y,ies}",
  ["hypothetical"] = "hipothetical",
  ["identifier"] = "identfiier",
  ["identity"] = "identitiy",
  ["idiosyncrasy"] = "idiosyncracy",
  ["ignore"] = "ignroe",
  ["imagination{}"] = "imaginaton{,s}",
  ["immediately"] = "immediatley",
  ["immediate{}"] = "immediat{,ly}",
  ["immunit{}"] = "imunit{y,ies}",
  ["immutability"] = "immutabilty",
  ["immutable"] = "immutible",
  ["implementation{}"] = "implimentation{,s}",
  ["import"] = "imoprt",
  ["important"] = "importnat",
  ["inaccessible"] = "inaccesible",
  ["inadvertent{}"] = "inadvertant{,ly}",
  ["incidentally"] = "incidently",
  ["include"] = "incldue",
  ["increase"] = "increaes",
  ["incredible"] = "incrediable",
  ["independence"] = "independance",
  ["independent"] = "independant",
  ["indictment{}"] = "inditement{,s}",
  ["indispensa{}"] = "indispensi{ble,bly}",
  ["inevita{}"] = "ineviti{ble,bly}",
  ["infinite{}"] = "infinate{,ly}",
  ["infinit{}"] = "infint{e,ely}",
  ["influence"] = "influance",
  ["information"] = "{infomration,informaiton}",
  ["infrastructure{}"] = "infastructure{,s}",
  ["infrastructur{}"] = "infrastuctur{e,es}",
  ["inheritance{}"] = "inheritence{,s}",
  ["initial"] = "intial",
  ["initialization{}"] = "initilization{,s}",
  ["initialize"] = "initialze",
  ["initially"] = "initally",
  ["innocent"] = "inocent",
  ["innocuous"] = "inocuous",
  ["inoculat{}"] = "innoculat{e,es,ed,ing}",
  ["inside"] = "indise",
  ["install"] = "isntall",
  ["installation"] = "instalation",
  ["instance"] = "instnace",
  ["instantiat{}"] = "instanciat{e,es,ed,ing}",
  ["instead"] = "instaed",
  ["instruction{}"] = "instrucion{,s}",
  ["instructio{}"] = "intructio{n,ns}",
  ["integer{}"] = "interger{,s}",
  ["intege{}"] = "intge{r,rs}",
  ["integrate"] = "intergrate",
  ["integrity"] = "integrety",
  ["intellectual{}"] = "intelectual{,s,ly}",
  ["intelligence"] = "inteligence",
  ["intentionally"] = "intentionaly",
  ["interchangeable"] = "interchangable",
  ["interesting"] = "intresting",
  ["interface"] = "interafce",
  ["intermittent"] = "intermitent",
  ["interoperability"] = "interoprability",
  ["interpretation{}"] = "intepretation{,s}",
  ["interpreter{}"] = "interpretter{,s}",
  ["interprete{}"] = "inteprete{r,rs}",
  ["interrupt{}"] = "interupt{,s,ed,ing,ion,ions}",
  ["interrup{}"] = "intterup{t,ts,ted,ting,tion,tions}",
  ["into"] = "itno",
  ["invariant{}"] = "invarient{,s}",
  ["irrelevant"] = "irrelevent",
  ["irresisti{}"] = "irresista{ble,bly}",
  ["irreversible"] = "irreversable",
  ["issue"] = "isuse",
  ["iteration{}"] = "iteraton{,s}",
  ["iteratio{}"] = "iteratoi{n,ns}",
  ["just"] = "jsut",
  ["keyboard"] = "keybaord",
  ["knowledge"] = "{knoledge,knowlege}",
  ["knowledgeable"] = "knowledgable",
  ["k{now}{}"] = "k{nwo,onw}{,s,ing,n}",
  ["laborator{}"] = "labrator{y,ies}",
  ["language"] = "langauge",
  ["latenc{}"] = "latanc{y,ies}",
  ["later"] = "laetr",
  ["leave"] = "levae",
  ["legitimate{}"] = "legitmate{,ly}",
  ["leisure"] = "liesure",
  ["length"] = "lenght",
  ["lethal{}"] = "leathal{,ly}",
  ["liaison"] = "liason",
  ["libraries"] = "{libaries,librays}",
  ["library"] = "lib{ary,ray}",
  ["license"] = "{liscense,lisence}",
  ["lifecycle{}"] = "lifecyle{,s}",
  ["lifecycl{}"] = "lifcycl{e,es}",
  ["like"] = "liek",
  ["likely"] = "likley",
  ["literally"] = "literaly",
  ["little"] = "littel",
  ["local"] = "lcoal",
  ["logical"] = "logcial",
  ["loneliness"] = "lonliness",
  ["long"] = "lnog",
  ["machine"] = "mahcine",
  ["made"] = "maed",
  ["magazine{}"] = "magasine{,s}",
  ["magnificent{}"] = "magnificant{,ly}",
  ["maintenance"] = "{maintainance,maintenence}",
  ["mak{}"] = "mka{e,es,er,ers,ing}",
  ["managea{}"] = "managa{ble,bility}",
  ["management"] = "{managment,mangement}",
  ["manifest{}"] = "manfest{,s}",
  ["manifes{}"] = "mainfes{t,ts}",
  ["manually"] = "{manaully,manualy}",
  ["many"] = "mnay",
  ["mathematical{}"] = "mathmatical{,ly}",
  ["mathematics"] = "mathmatics",
  ["maximum"] = "{maximun,maxium}",
  ["mechanism{}"] = "mechinism{,s}",
  ["mechanis{}"] = "mecanis{m,ms}",
  ["medicine{}"] = "medecine{,s}",
  ["medieval"] = "{medeval,mideval}",
  ["mediocre"] = "medioker",
  ["memento{}"] = "mamento{,s}",
  ["memory"] = "{memmory,memroy}",
  ["message{}"] = "mesage{,s}",
  ["messag{}"] = "messeg{e,es}",
  ["metadata"] = "{meatdata,metdata}",
  ["method{}"] = "mehtod{,s}",
  ["middleware"] = "middlware",
  ["might"] = "migth",
  ["millennium"] = "{milennium,millenium}",
  ["millionaire{}"] = "millioniare{,s}",
  ["miniature{}"] = "miniture{,s}",
  ["minimum"] = "minumum",
  ["miscellaneou{}"] = "miscellaniou{s,sly}",
  ["mischievous{}"] = "mischievious{,ly}",
  ["misc{ellaneous}{}"] = "misc{elaneous,ellanous}{,ly}",
  ["missile{}"] = "missle{,s}",
  ["misspell{}"] = "mispell{,s,ed,ing}",
  ["model"] = "modle",
  ["modify"] = "modfiy",
  ["module{}"] = "moduel{,s}",
  ["modul{}"] = "moudl{e,es}",
  ["modu{}"] = "mdu{le,les}",
  ["monaster{}"] = "monestar{y,ies}",
  ["more"] = "moer",
  ["mortgage{}"] = "morgage{,s,d}",
  ["most"] = "msot",
  ["much"] = "mcuh",
  ["multiple"] = "mulitple",
  ["name"] = "naem",
  ["namespace{}"] = "namesapce{,s}",
  ["namespac{}"] = "namspac{e,es}",
  ["name{s}{}"] = "name{}{pace,paces}",
  ["narrative{}"] = "narative{,s}",
  ["natural"] = "{natrual,natual}",
  ["navigation"] = "{navagation,navgiation}",
  ["necessarily"] = "necesarily",
  ["necessary"] = "necesary",
  ["necessar{}"] = "neccessar{y,ily}",
  ["negligible"] = "{neglible,negligable}",
  ["neighbor"] = "nieghbor",
  ["neither"] = "{neiter,niether}",
  ["never"] = "{neevr,nevre}",
  ["new"] = "nwe",
  ["next"] = "enxt",
  ["ninety"] = "ninty",
  ["normally"] = "normaly",
  ["normal{}"] = "norml{,ly}",
  ["norma{}"] = "nomra{l,lly}",
  ["noticeable"] = "noticable",
  ["noticeably"] = "noticably",
  ["notification"] = "notifcation",
  ["nuclear"] = "nucular",
  ["number"] = "nubmer",
  ["obedience"] = "obediance",
  ["obstacle{}"] = "obstacal{,s}",
  ["obvious"] = "{obivous,obvoius}",
  ["occasion"] = "occassion",
  ["occasionally"] = "{ocassionally,occassionally}",
  ["occasioned"] = "occassioned",
  ["occurrence{}"] = "occurance{,s}",
  ["occurrenc{}"] = "occurenc{e,es}",
  ["occurre{}"] = "occurra{nce,nces}",
  ["occurr{}"] = "occur{ed,ing}",
  ["oc{}"] = "o{casion,casioned,casionally}",
  ["official{}"] = "offical{,ly}",
  ["officia{}"] = "oficia{l,lly}",
  ["often"] = "ofetn",
  ["omission"] = "ommission",
  ["omitt{}"] = "omit{ed,ing}",
  ["once"] = "ocne",
  ["one{}"] = "oen{,self}",
  ["only"] = "onyl",
  ["operator"] = "operater",
  ["operator{}"] = "opperator{,s}",
  ["opportunit{}"] = "oportunit{y,ies}",
  ["opportuni{}"] = "oppurtuni{ty,ties}",
  ["optimization{}"] = "optimzation{,s}",
  ["optional"] = "optinal",
  ["option{}"] = "optoin{,s}",
  ["order"] = "ordre",
  ["originally"] = "originaly",
  ["original{}"] = "orginal{,ly}",
  ["other"] = "otehr",
  ["overrid{}"] = "overid{e,es,ing}",
  ["overri{}"] = "ovverri{de,des,ding}",
  ["package{}"] = "pakcage{,s,d}",
  ["parallel"] = "paralell",
  ["parallel{}"] = "paralel{,s,ed,ing,ism}",
  ["parameter"] = "paramater",
  ["parameterized"] = "paramaterized",
  ["parameter{}"] = "paramter{,ized}",
  ["parliament"] = "parliment",
  ["parsing"] = "parseing",
  ["participant{}"] = "partcipant{,s}",
  ["participan{}"] = "paricipan{t,ts}",
  ["particular"] = "particualr",
  ["pastime{}"] = "passtime{,s}",
  ["pattern{}"] = "patern{,s,ed,ing}",
  ["patte{}"] = "patt{rn,rns,rned,rning}",
  ["pavilion{}"] = "pavillion{,s}",
  ["peculiar{}"] = "paculier{,ly}",
  ["people"] = "{peopel,poeple}",
  ["perceiv{}"] = "perciev{e,es,ed,ing}",
  ["performance"] = "perfomance",
  ["perhaps"] = "{perhpas,prehaps}",
  ["permanent{}"] = "permanant{,ly}",
  ["permanen{}"] = "permenan{t,tly}",
  ["permissible"] = "permissable",
  ["permission"] = "{permision,permisson}",
  ["perseverance"] = "{perseverence,perserverance}",
  ["persistence"] = "{persistance,persitence}",
  ["persistent"] = "{persistant,persitent}",
  ["personnel"] = "{personell,personnell}",
  ["persuad{}"] = "pursuad{e,es,ed,ing}",
  ["pharaoh{}"] = "pharoah{,s}",
  ["phenomena"] = "phenonmena",
  ["phenomenon"] = "phenomonon",
  ["piece{}"] = "peice{,s}",
  ["pigeon{}"] = "pidgeon{,s}",
  ["plac{}"] = "palc{e,es,ed,ing}",
  ["playwright{}"] = "playwrite{,s}",
  ["pleasant{}"] = "pleasent{,ly}",
  ["please"] = "plaese",
  ["point"] = "poitn",
  ["politician{}"] = "politican{,s}",
  ["polymorphism"] = "polymoprhism",
  ["position"] = "postion",
  ["positional"] = "positonal",
  ["possession"] = "posession",
  ["possess{}"] = "posess{,es,ed,ing,ive}",
  ["possibilit{}"] = "possibilt{y,ies}",
  ["possible"] = "posible",
  ["potatoes"] = "potatos",
  ["practically"] = "practicaly",
  ["precede"] = "preceed",
  ["precedence"] = "precendence",
  ["predecessor{}"] = "predecesor{,s}",
  ["prefera{}"] = "preferi{ble,bly}",
  ["preference"] = "preferance",
  ["preferr{}"] = "prefer{ed,ing}",
  ["prefer{}"] = "perfer{able,ably}",
  ["preparation"] = "preperation",
  ["prerequisite{}"] = "prerequsite{,s}",
  ["prerequisit{}"] = "prerequist{e,es}",
  ["prescription{}"] = "prescrition{,s}",
  ["presence"] = "{presance,presense}",
  ["preview"] = "{preivew,preveiw}",
  ["previous"] = "prevous",
  ["primary"] = "primayr",
  ["private"] = "{priavte,privte}",
  ["privilege{}"] = "priviledge{,s,d}",
  ["privileg{}"] = "priveleg{e,es,ed}",
  ["probably"] = "probaly",
  ["procedure{}"] = "proceedure{,s}",
  ["procedur{}"] = "procedr{e,es}",
  ["proceed{,s,ed,ing}"] = "procede{,s,d,ing}",
  ["process{}"] = "proccess{,es,ed,ing}",
  ["production"] = "{prodcution,produciton}",
  ["professional"] = "{profesional,proffesional}",
  ["professor{}"] = "proffessor{,s}",
  ["professo{}"] = "profeso{r,rs}",
  ["projec{}"] = "projc{t,ts,ted,ting,tor,tors}",
  ["promise{}"] = "promisse{,s,d}",
  ["promising"] = "promissing",
  ["pronounc{}"] = "pronouc{e,es,ed,ing}",
  ["pronunciation{}"] = "pronounciation{,s}",
  ["propaganda"] = "propoganda",
  ["propagat{}"] = "propogat{e,es,ed,ing,ion,ions}",
  ["propaga{}"] = "propega{te,tes,ted,ting,tion,tions}",
  ["propert{}"] = "propret{y,ies}",
  ["proposal"] = "proposel",
  ["proprietary"] = "propietary",
  ["protocol{}"] = "protocal{,s}",
  ["protoco{l}{}"] = "protoca{ll}{,s}",
  ["provide"] = "{porvide,provdie}",
  ["publicly"] = "publically",
  ["purpose"] = "purpsoe",
  ["p{lugin}{}"] = "p{lguin,ulgin}{,s}",
  ["p{roblem}{}"] = "p{robelm,orblem}{,s}",
  ["p{roject}{}"] = "p{roejct,orject}{,s,ed,ing,or,ors}",
  ["quantit{}"] = "quanit{y,ies}",
  ["quanti{}"] = "quanta{ty,ties}",
  ["query"] = "qeury",
  ["question"] = "quesiton",
  ["questionable"] = "quesitonable",
  ["questionnaire"] = "questionaire",
  ["readability"] = "readabilty",
  ["readable"] = "readible",
  ["really"] = "{realy,relaly}",
  ["real{}"] = "rael{,ly}",
  ["reaso{}"] = "reso{n,ns,ned,ning,nable,nably}",
  ["receipt{}"] = "reciept{,s}",
  ["receiv{}"] = "reciev{e,es,ed,ing}",
  ["recei{}"] = "rece{ve,ves,ved,ving}",
  ["recent"] = "recnet",
  ["rece{i}{}"] = "reci{}{ve,ves,ved,ving}",
  ["recognition"] = "recoginition",
  ["recognize"] = "{recongize,reconize}",
  ["recommend{}"] = "recomend{,s,ed,ing,ation,ations}",
  ["recommen{}"] = "reccommen{d,ds,ded,ding,dation,dations}",
  ["reconnaissance"] = "{reconaissance,reconnaisance}",
  ["recursive"] = "{recrusive,recusive}",
  ["refactor{}"] = "refacotr{,s,ed,ing}",
  ["referr{}"] = "refer{ed,ing,al}",
  ["refrigerator{}"] = "refridgerator{,s}",
  ["ref{erence}{}"] = "ref{erecne,rence}{,s}",
  ["regression{}"] = "regresion{,s}",
  ["relationship"] = "relashionship",
  ["relevant"] = "{relavent,relevent}",
  ["reliability"] = "realiability",
  ["religious{}"] = "religous{,ly}",
  ["remember"] = "{remeber,remenber}",
  ["remembrance{}"] = "rememberance{,s}",
  ["remove"] = "{remvoe,reomve}",
  ["renderer{}"] = "renderor{,s}",
  ["repetition"] = "{repeatition,repetion}",
  ["replace"] = "{relpace,repalce}",
  ["repositories"] = "{repositroies,respositories}",
  ["repository"] = "{repositroy,respository}",
  ["representative{}"] = "representive{,s}",
  ["request{}"] = "reqeust{,s,ed,ing}",
  ["reques{}"] = "requs{t,ts,ted,ting}",
  ["require"] = "requrie",
  ["required"] = "requried",
  ["requirement{}"] = "requirment{,s}",
  ["requi{}"] = "requ{re,red,rement,rements}",
  ["req{uest,uests,uested,uesting}"] = "req{uset,usets,useted,useting}",
  ["resilience"] = "resiliance",
  ["resistance{}"] = "resistence{,s}",
  ["resolution"] = "{reslution,resoluton}",
  ["resource{}"] = "resouce{,s}",
  ["resourc{}"] = "resorc{e,es}",
  ["response{}"] = "reponse{,s}",
  ["responsibilit{}"] = "responsabilit{y,ies}",
  ["responsible"] = "responcible",
  ["respons{}"] = "repsons{e,es}",
  ["respon{s}{}"] = "respon{c}{e,es}",
  ["rest{aurant}{}"] = "rest{araunt,urant}{,s}",
  ["result"] = "resutl",
  ["retrieve"] = "{retreive,retrive}",
  ["return"] = "reutrn",
  ["re{ason}{}"] = "re{aosn,saon}{,s,ed,ing,able,ably}",
  ["rhythm{}"] = "rythm{,s}",
  ["ridiculous{}"] = "rediculous{,ly}",
  ["right"] = "rigth",
  ["running"] = "runing",
  ["runtime{}"] = "rumtime{,s}",
  ["r{hythm}{}"] = "r{hytm,ythym}{,s}",
  ["sacrific{}"] = "sacrafic{e,es,ed,ing}",
  ["sacrilegious"] = "sacreligious",
  ["safety"] = "saftey",
  ["said"] = "siad",
  ["same"] = "smae",
  ["sandwich{}"] = "sandwhich{,es}",
  ["satellite{}"] = "satelite{,s}",
  ["satellit{}"] = "sattelit{e,es}",
  ["scenario{}"] = "scenerio{,s}",
  ["schedul{}"] = "shedul{e,es,ed,ing}",
  ["schedu{}"] = "schdu{le,les,led,ling}",
  ["schema{}"] = "scema{,s}",
  ["scissors"] = "sissors",
  ["screenshot{}"] = "screensot{,s}",
  ["screensho{}"] = "scrensho{t,ts}",
  ["secretary"] = "secretery",
  ["section{}"] = "seciton{,s}",
  ["sectio{}"] = "secto{n,ns}",
  ["security"] = "{securtiy,securty}",
  ["seizure{}"] = "siezure{,s}",
  ["semaphore{}"] = "sempahore{,s}",
  ["sentence"] = "{sentance,sentense}",
  ["separator{}"] = "seperator{,s}",
  ["separat{}"] = "seperat{e,es,ed,ing,ion,ions,ely}",
  ["sequence"] = "sequnce",
  ["serialization{}"] = "serializaton{,s}",
  ["server"] = "srever",
  ["setting"] = "{seting,setitng}",
  ["several"] = "{sevaral,severl}",
  ["should"] = "shoudl",
  ["siege"] = "seige",
  ["significance"] = "{signficance,signifcance}",
  ["significant"] = "signifcant",
  ["significantly"] = "signficantly",
  ["similar{}"] = "similiar{,ity,ly}",
  ["simila{}"] = "simla{r,rity,rly}",
  ["simple"] = "simpel",
  ["simultaneous{}"] = "simultanious{,ly}",
  ["since"] = "sicne",
  ["sincerely"] = "sincerly",
  ["small"] = "samll",
  ["software"] = "{sofware,sofwtare,sotfware}",
  ["somebody"] = "{somebdoy,somebdy,sombody}",
  ["someday"] = "somday",
  ["somehow"] = "{somehwo,somhow}",
  ["someone"] = "{someoen,somone}",
  ["someplace"] = "somepalce",
  ["sometime"] = "sometmie",
  ["somewhat"] = "somewaht",
  ["somewhere"] = "somehwere",
  ["som{ething}{}"] = "som{ehting,ethign,ethng,thing}{,s}",
  ["sophisticat{}"] = "sophisiticat{e,es,ed,ing}",
  ["source"] = "{souce,soucre}",
  ["souvenir{}"] = "souvenier{,s}",
  ["sover{eign,eignty}"] = "sover{ign,ignty}",
  ["specific"] = "specifc",
  ["specifically"] = "specificly",
  ["specification{}"] = "specifcation{,s}",
  ["specify"] = "specifiy",
  ["specimen"] = "speciman",
  ["speech"] = "speach",
  ["standard"] = "standad",
  ["state"] = "staet",
  ["statement"] = "{statemnt,statment}",
  ["statistics"] = "statistcs",
  ["still"] = "sitll",
  ["strategies"] = "{starategies,stratgeies}",
  ["strategy"] = "{starategy,stratgey}",
  ["strength"] = "{stregth,strenght}",
  ["string"] = "{stirng,strng}",
  ["structur{}"] = "strucutr{e,es,ed,ing}",
  ["struc{}"] = "sturc{ture,tures,tured,turing}",
  ["subclass{}"] = "sublcass{,es}",
  ["subprocess{}"] = "subproccess{,es}",
  ["successful{}"] = "succesful{,ly}",
  ["succession{}"] = "succesion{,s}",
  ["such"] = "suhc",
  ["sufficient"] = "{sufficent,suficient}",
  ["summary"] = "{sumary,summay}",
  ["superintendent{}"] = "superintendant{,s}",
  ["supersede"] = "{supercede,superseed}",
  ["support"] = "supoprt",
  ["suppress{}"] = "supress{,es,ed,ing,ion,ions}",
  ["surprise"] = "suprise",
  ["surveillance"] = "surveilance",
  ["synchronization"] = "syncronization",
  ["synchronous"] = "syncronous",
  ["syntax"] = "sytnax",
  ["syn{}"] = "sy{chronous,chronization}",
  ["system"] = "sytem",
  ["s{ome}{}"] = "{smoe,soem}{,body,day,how,one,place,thing,time,what,where}",
  ["tak{}"] = "tka{e,es,en,ing}",
  ["technical{}"] = "tecnical{,ly}",
  ["technica{}"] = "techinca{l,lly}",
  ["technology"] = "{technolgy,techology}",
  ["temperament"] = "temperment",
  ["templat{}"] = "tempalt{e,es,ed,ing}",
  ["templa{}"] = "temple{te,tes,ted,ting}",
  ["temporary"] = "temperary",
  ["tem{perature}{}"] = "tem{pature,perture}{,s}",
  ["tendency"] = "tendancy",
  ["terminal"] = "{temrinal,termial}",
  ["testing"] = "testign",
  ["than"] = "thna",
  ["that"] = "taht",
  ["their"] = "thier",
  ["themselves"] = "themselfs",
  ["the{}"] = "hte{,ir,m,mselves,n,re,se,y}",
  ["this"] = "{thsi,tihs}",
  ["those"] = "thsoe",
  ["threshold{}"] = "threshhold{,s}",
  ["threshol{}"] = "thresol{d,ds}",
  ["throughout"] = "througout",
  ["throughput"] = "thoughput",
  ["through{}"] = "throgh{,out,put}",
  ["th{e,eir,em,emselves,en,ere,ese,ey}"] = "teh{,ir,m,mselves,n,re,se,y}",
  ["th{rough}{}"] = "th{orugh,rouhg}{,out}",
  ["time"] = "tiem",
  ["timeout"] = "{tiemout,timout}",
  ["together"] = "{togehter,togheter,togther}",
  ["token"] = "toekn",
  ["tolerance"] = "tolerence",
  ["tomorrow"] = "{tommorow,tommorrow}",
  ["tournament{}"] = "tournement{,s}",
  ["tragedy"] = "tradgedy",
  ["transaction{}"] = "transction{,s}",
  ["transactio{}"] = "transacio{n,ns}",
  ["transfer"] = "tranfer",
  ["transferr{}"] = "transfer{ed,ing}",
  ["transformation{}"] = "tranformation{,s}",
  ["transformatio{}"] = "transfromatio{n,ns}",
  ["trans{fer,ferred,ferring}"] = "trasn{fer,fered,fering}",
  ["trans{}"] = "tras{fer,ferred,ferring}",
  ["treatment{}"] = "treatement{,s}",
  ["trigger"] = "triger",
  ["troubleshooting"] = "toubleshooting",
  ["true"] = "ture",
  ["truly"] = "truely",
  ["twelfth"] = "twelth",
  ["typ{}"] = "tpy{e,es,ed,ing}",
  ["tyrann{}"] = "tyran{y,ies}",
  ["ty{p}{}"] = "ty{pp}{e,es,ed,ing}",
  ["t{hing}{}"] = "{hting,thign,thnig,tihng}{,s}",
  ["t{hink}{}"] = "{htink,thikn,thnik,tihnk}{,ing,s}",
  ["ubiquitous"] = "{ubiquitious,ubiquotous}",
  ["unanimous"] = "unanymous",
  ["unavailable"] = "unavaliable",
  ["unconstitutional"] = "uncontitutional",
  ["undefined"] = "{undefiend,undefind}",
  ["under"] = "udner",
  ["understand"] = "{understnad,undestand}",
  ["unforeseen"] = "unforseen",
  ["unfortunately"] = "unfortunatly",
  ["unfortunate{}"] = "unfortuante{,ly}",
  ["unfortunat{}"] = "unforunat{e,ely}",
  ["unique{}"] = "unqiue{,ly}",
  ["uniqu{}"] = "uniq{e,ely}",
  ["unknown{}"] = "uknown{,s}",
  ["unk{nown}{}"] = "unk{nwon,own}{,s}",
  ["unnecessar{}"] = "unecessar{y,ily}",
  ["until"] = "untill",
  ["unusual"] = "unusal",
  ["update"] = "{udpate,upadte}",
  ["useful"] = "{usefl,usefull}",
  ["using"] = "{uisng,useing,usign}",
  ["usually"] = "{usally,usualy}",
  ["us{}"] = "ues{e,es,ed,er,ers,ing}",
  ["utility"] = "utilty",
  ["utilit{}"] = "utillit{y,ies}",
  ["vac{uum}{}"] = "vac{cum,um}{,s,ed,ing}",
  ["validate"] = "{valdate,validte}",
  ["value{}"] = "vlaue{,s}",
  ["valu{}"] = "vau{e,es}",
  ["variable{}"] = "varible{,s}",
  ["various"] = "{varios,varous}",
  ["vegetable{}"] = "vegtable{,s}",
  ["vegetabl{}"] = "vegatabl{e,es}",
  ["vehicle{}"] = "vehical{,s}",
  ["vehicl{}"] = "veicl{e,es}",
  ["version"] = "verison",
  ["very"] = "vrey",
  ["vicious{}"] = "visious{,ly}",
  ["villain{}"] = "villian{,s}",
  ["visibility"] = "{visibilty,visiblity}",
  ["visible"] = "{visable,visble}",
  ["vulnerabilit{}"] = "vulnerabilt{y,ies}",
  ["vulnerabil{}"] = "vulnerabl{ity,ities}",
  ["want"] = "wnat",
  ["warrant{}"] = "warrent{y,ies}",
  ["warran{}"] = "waran{ty,ties}",
  ["was"] = "wsa",
  ["wednesday"] = "wendesday",
  ["weird{}"] = "wierd{,ly}",
  ["weir{}"] = "weer{d,dly}",
  ["what"] = "{waht,whta}",
  ["when"] = "wehn",
  ["where"] = "wehre",
  ["which"] = "whcih",
  ["while"] = "wihle",
  ["whitespace"] = "{whitepace,whitesapce}",
  ["whole"] = "wohle",
  ["will{}"] = "iwll{,s,ed,ing}",
  ["wil{l,ls,led,ling}"] = "wlil{,s,ed,ing}",
  ["window"] = "{widnow,winodw}",
  ["with{}"] = "wiht{,in,out}",
  ["wit{h,hin,hout}"] = "wtih{,in,out}",
  ["wonderful"] = "wonderfull",
  ["word{}"] = "wrod{,s}",
  ["wore"] = "wroe",
  ["workflow"] = "{worflow,worklfow}",
  ["working"] = "wokring",
  ["work{}"] = "wrok{,s,ed,er,ers,ing}",
  ["world{}"] = "wrold{,s,wide}",
  ["worl{}"] = "wolr{d,ds,dwide}",
  ["worm{}"] = "wrom{,s,ed,ing}",
  ["worn"] = "wron",
  ["worr{}"] = "wror{y,ies,ied,ying}",
  ["worship{}"] = "wroship{,s,ed,er,ers,ing}",
  ["wors{}"] = "wros{e,t}",
  ["worthy"] = "wrothy",
  ["wor{}"] = "wot{k,ks,ked,ker,kers,king}",
  ["would"] = "woudl",
  ["write{}"] = "wriet{,s}",
  ["writing"] = "{writng,writting}",
  ["writ{}"] = "wirt{e,es,er,ers,ing}",
  ["wri{t}{}"] = "wrt{i}{e,es}",
  ["yacht{}"] = "yatch{,s}",
  ["year"] = "yaer",
  ["yield"] = "yeild",
  ["you"] = "yuo",
  ["your"] = "yuor",
  ["zealous{}"] = "zelous{,ly}",
  ["{accompanies,accompanied,accompanying}"] = "{acompanies,acompanied,acompanying}",
  ["{default}"] = "{defaut}",
  ["{define,defines,defining}"] = "{deifne,deifnes,deifning}",
  ["{difficult,difficulty,difficulties}"] = "{diffcult,diffculty,diffculties}",
  ["{happen,happens,happened,happening}"] = "{happpen,happpens,happpened,happpening}",
}

local function split_alternatives(value)
  local alternatives = {}
  local start = 1

  while true do
    local comma = value:find(",", start, true)
    if not comma then
      table.insert(alternatives, value:sub(start))
      return alternatives
    end

    table.insert(alternatives, value:sub(start, comma - 1))
    start = comma + 1
  end
end

local function brace_parts(value)
  local open = value:find("{", 1, true)
  if not open then
    assert(not value:find("}", 1, true), ("Unmatched } in %q"):format(value))
    return nil
  end

  local close = value:find("}", open + 1, true)
  assert(close, ("Unmatched { in %q"):format(value))
  assert(
    not value:sub(open + 1, close - 1):find("{", 1, true),
    ("Nested braces are not supported in %q"):format(value)
  )

  return value:sub(1, open - 1),
    value:sub(open + 1, close - 1),
    value:sub(close + 1)
end

local function expand_braces(lhs, rhs)
  local expanded = {}
  local pending = { { lhs = lhs, rhs = rhs } }

  while #pending > 0 do
    local entry = table.remove(pending)
    local lhs_before, lhs_middle, lhs_after = brace_parts(entry.lhs)

    if not lhs_before then
      assert(
        not brace_parts(entry.rhs),
        ("Replacement has more brace pairs than %q"):format(lhs)
      )
      expanded[entry.lhs] = entry.rhs
    else
      local targets = split_alternatives(lhs_middle)
      local rhs_before, rhs_middle, rhs_after = brace_parts(entry.rhs)
      local replacements = rhs_middle and split_alternatives(rhs_middle) or nil

      -- An empty replacement pair aliases the corresponding alternatives from
      -- the left-hand side, as in: seperate{,ly} -> separate{}.
      if replacements and #replacements == 1 and replacements[1] == "" then
        replacements = targets
      end

      for index, target in ipairs(targets) do
        local replacement = entry.rhs
        if replacements then
          replacement = rhs_before
            .. replacements[((index - 1) % #replacements) + 1]
            .. rhs_after
        end

        table.insert(pending, {
          lhs = lhs_before .. target .. lhs_after,
          rhs = replacement,
        })
      end
    end
  end

  return expanded
end

local function title_case(word)
  return word:sub(1, 1):upper() .. word:sub(2)
end

local function expand_corrections(entries)
  local expanded = {}

  for correction, variants in pairs(entries) do
    for typo, expanded_correction in pairs(expand_braces(variants, correction)) do
      assert(
        typo ~= expanded_correction,
        ("Correction maps %q to itself"):format(typo)
      )
      assert(
        expanded[typo] == nil or expanded[typo] == expanded_correction,
        ("Conflicting corrections for %q"):format(typo)
      )
      expanded[typo] = expanded_correction
    end
  end

  return expanded
end

local function with_case_variants(entries)
  local variants = {}

  for typo, correction in pairs(entries) do
    variants[typo] = correction
    variants[title_case(typo)] = title_case(correction)
    variants[typo:upper()] = correction:upper()
  end

  return variants
end

local case_aware_corrections =
  with_case_variants(expand_corrections(corrections))

-- Use an allowlist so intentionally unusual identifiers remain untouched in code.
local enabled_filetypes = {
  gitcommit = true,
  markdown = true,
}

local function install(bufnr)
  if vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo, correction in pairs(case_aware_corrections) do
    vim.keymap.set("ia", typo, correction, {
      buffer = bufnr,
      desc = ("Correct %s to %s"):format(typo, correction),
      noremap = true,
    })
  end

  vim.b[bufnr].prose_abbreviations_installed = true
end

local function uninstall(bufnr)
  if not vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo in pairs(case_aware_corrections) do
    vim.keymap.del("ia", typo, { buffer = bufnr })
  end

  vim.b[bufnr].prose_abbreviations_installed = nil
end

function M.setup()
  vim.api.nvim_create_autocmd({ "BufEnter", "FileType" }, {
    group = vim.api.nvim_create_augroup(
      "ProseAbbreviations",
      { clear = true }
    ),
    callback = function(event)
      local enabled = enabled_filetypes[vim.bo[event.buf].filetype] == true
      if enabled then
        install(event.buf)
      else
        uninstall(event.buf)
      end
    end,
  })
end

return M
