local M = {}

-- Keep this list curated: every entry is applied automatically, not suggested,
-- so a typo variant must never be a correctly spelled word.
-- Keys are correct spellings and values are their typo variants. Every key uses
-- the same syntax so the declarations can be sorted lexicographically.
-- Brace alternatives are paired by position. An empty pair on the correct side
-- copies the typo suffixes, so ["separate{}"] = "seperate{,ly}" expands to
-- seperate -> separate and seperately -> separately.
-- Multiple pairs form a product, so ["s{ome}{}"] =
-- "{smoe,soem}{,body}" also covers smoe, soem, smoebody, and soembody.
local corrections = {
  ["abandonment"] = "abandonnment",
  ["abbreviation"] = "abreviation",
  ["ability"] = "abiltiy",
  ["about"] = "{abotu,baout}",
  ["above"] = "abvoe",
  ["absence"] = "absense",
  ["absolutely"] = "absolutley",
  ["academic"] = "acadmic",
  ["accelerat{e,es,ed,ing,ion,ions}"] = "acelerat{e,es,ed,ing,ion,ions}",
  ["accept"] = "acecpt",
  ["acceptable"] = "acceptible",
  ["accessible"] = "acessible",
  ["accessor{y,ies}"] = "acessor{y,ies}",
  ["accidentally"] = "{accidentaly,accidently}",
  ["accommodat{e,es,ed,ing,ion,ions}"] = "accomodat{e,es,ed,ing,ion,ions}",
  ["according"] = "acording",
  ["accuracy"] = "accuracey",
  ["achiev{e,es,ed,ing,ement,ements}"] = "acheiv{e,es,ed,ing,ement,ements}",
  ["acknowledge"] = "acknowlege",
  ["acquaintance"] = "{acquaintence,aquaintance}",
  ["acquire"] = "aquire",
  ["acquisition"] = "aquisition",
  ["across"] = "accross",
  ["action"] = "atcion",
  ["activate"] = "activte",
  ["activit{y,ies}"] = "activt{y,ies}",
  ["actual{,ly}"] = "{acutal,actualy}",
  ["additional"] = "additonal",
  ["address{}"] = "adress{,es,ed,ing}",
  ["adequate"] = "adequete",
  ["adjacent"] = "adjecent",
  ["administrator"] = "adminstrator",
  ["advanced"] = "advnaced",
  ["advantage"] = "advatnage",
  ["advertisement"] = "advertisment",
  ["advice"] = "adivce",
  ["advisable"] = "adviseable",
  ["after"] = "afetr",
  ["again"] = "agian",
  ["against"] = "agianst",
  ["aggressive"] = "agressive",
  ["alcohol"] = "alcohal",
  ["algorithm"] = "algorithim",
  ["allegiance"] = "allegience",
  ["allocat{e,es,ed,ing,ion,ions}"] = "alocat{e,es,ed,ing,ion,ions}",
  ["allotted"] = "alloted",
  ["along"] = "alnog",
  ["already"] = "aleady",
  ["also"] = "aslo",
  ["although"] = "althought",
  ["always"] = "alwasy",
  ["amateur"] = "amature",
  ["amendment{}"] = "ammendment{,s}",
  ["among"] = "amoung",
  ["amount"] = "ammount",
  ["analysis"] = "analisis",
  ["analytically"] = "analyticly",
  ["anniversary"] = "{aniversay,aniversary}",
  ["announcement{}"] = "announcment{,s}",
  ["annual"] = "anual",
  ["anonymous"] = "anonymus",
  ["another"] = "anohter",
  ["answer"] = "anwser",
  ["anticipate"] = "anticiapte",
  ["anybody"] = "{anybdoy,anybdy}",
  ["anyhow"] = "anyhwo",
  ["anyone"] = "anyoen",
  ["anyplace"] = "anypalce",
  ["anything"] = "{anyhting,anythign,anyting}",
  ["anytime"] = "anytmie",
  ["anyway"] = "anyawy",
  ["anywhere"] = "anyhwere",
  ["apolog{y,ies}"] = "appolog{y,ies}",
  ["apparatus"] = "aparatus",
  ["apparent"] = "apparant",
  ["apparently"] = "{aparently,apparantly}",
  ["appearance"] = "appearence",
  ["appendix"] = "apendix",
  ["application"] = "applicaiton",
  ["appreciat{e,es,ed,ing,ion,ions}"] = "apreciat{e,es,ed,ing,ion,ions}",
  ["appropriate"] = "appropiate",
  ["approximately"] = "aproximatly",
  ["arbitrary"] = "arbitary",
  ["architecture"] = "architechture",
  ["argument"] = "arugment",
  ["argument{}"] = "arguement{,s}",
  ["around"] = "aroudn",
  ["arrangement"] = "arrangment",
  ["article"] = "artilce",
  ["assassination{}"] = "assasination{,s}",
  ["assignment"] = "assigment",
  ["assistance"] = "assitance",
  ["assistant"] = "assitant",
  ["association"] = "assocation",
  ["asynchronous"] = "asyncronous",
  ["attendance{}"] = "attendence{,s}",
  ["attention"] = "attension",
  ["audience"] = "audiance",
  ["author"] = "auhtor",
  ["authorization"] = "authorizaton",
  ["auxiliary"] = "auxillary",
  ["availability"] = "availablity",
  ["available"] = "{avaliable,availble}",
  ["awesome"] = "aweosme",
  ["back"] = "bakc",
  ["background"] = "backgroud",
  ["basic{,ally}"] = "{basci,basicly}",
  ["beautiful"] = "{beautifull,beutiful}",
  ["because"] = "becuase",
  ["become"] = "becmoe",
  ["before"] = "beofre",
  ["beginner"] = "beginer",
  ["beginning"] = "{beggining,begining}",
  ["being"] = "{beign,bieng}",
  ["believe"] = "{beleive,bleiev}",
  ["benefit{}"] = "benifit{,s,ed,ing}",
  ["better"] = "betetr",
  ["between"] = "betwen",
  ["boolean"] = "boolen",
  ["both"] = "btoh",
  ["boundary"] = "boundry",
  ["branch"] = "brnach",
  ["brief"] = "breif",
  ["bring"] = "birng",
  ["broccoli"] = "brocoli",
  ["build"] = "biuld",
  ["bureaucracy"] = "bureacracy",
  ["b{usiness}{}"] = "{buisness,bussiness}{,es}",
  ["callback"] = "calback",
  ["called"] = "caleld",
  ["camouflag{e,es,ed,ing}"] = "camoflag{e,es,ed,ing}",
  ["candidate"] = "canidate",
  ["capability"] = "capabilty",
  ["caribbean"] = "carribean",
  ["categor{y,ies}"] = "catagor{y,ies}",
  ["cause"] = "casue",
  ["ceiling{}"] = "cieling{,s}",
  ["cemetery"] = "cemetary",
  ["center"] = "cetner",
  ["certain"] = "certian",
  ["certificate"] = "certifcate",
  ["challenge"] = "chalenge",
  ["change"] = "chagne",
  ["changeable"] = "changable",
  ["chang{e,es,ed,ing}"] = "chnag{e,es,ed,ing}",
  ["character"] = "charactor",
  ["characteristic"] = "charateristic",
  ["check"] = "cehck",
  ["children"] = "chidlren",
  ["choice"] = "chioce",
  ["choose"] = "chosse",
  ["circuit{}"] = "circut{,s}",
  ["clear"] = "claer",
  ["close"] = "clsoe",
  ["code"] = "cdoe",
  ["coherent"] = "coherant",
  ["colleague"] = "collegue",
  ["column{}"] = "colum{,s}",
  ["combination"] = "combinaton",
  ["coming"] = "comming",
  ["command"] = "commnad",
  ["command{}"] = "comand{,s,ed,ing}",
  ["commercial{}"] = "comercial{,s}",
  ["commission{}"] = "comission{,s,ed,ing}",
  ["commitment{}"] = "comitment{,s}",
  ["committee"] = "comittee",
  ["committ{ed,ing}"] = "commit{ed,ing}",
  ["common"] = "comon",
  ["communication"] = "communciation",
  ["community"] = "comunity",
  ["comparative{}"] = "comparitive{,s,ly}",
  ["comparison"] = "comparision",
  ["compatibility"] = "compatability",
  ["competition{}"] = "competion{,s}",
  ["complete"] = "comlpete",
  ["completely"] = "completly",
  ["component"] = "compnoent",
  ["component{}"] = "componet{,s}",
  ["conced{e,es,ed,ing}"] = "conceed{,s,ed,ing}",
  ["conceivable"] = "concievable",
  ["conceiv{e,es,ed,ing}"] = "concie{ve,ves,ved,ving}",
  ["conclusion{}"] = "conclussion{,s}",
  ["concurrency"] = "concurency",
  ["condition{}"] = "conditon{,s,ed,ing}",
  ["confidence"] = "confidance",
  ["configuration"] = "configruation",
  ["configuration{}"] = "configuraiton{,s}",
  ["confirmation{}"] = "confirmaton{,s}",
  ["congratulations"] = "congradulations",
  ["connection"] = "conenction",
  ["connection{}"] = "conection{,s}",
  ["connoisseur{}"] = "conoisseur{,s}",
  ["conscientious"] = "concientious",
  ["conscious"] = "concious",
  ["consensus{}"] = "concensus{,es}",
  ["consequence{}"] = "consequnce{,s}",
  ["consider"] = "consdier",
  ["considerable"] = "considerible",
  ["consistent"] = "consistant",
  ["contain"] = "contian",
  ["content"] = "contnet",
  ["context"] = "{conetxt,cotnext}",
  ["continued"] = "continuted",
  ["continuous"] = "continous",
  ["control"] = "cotnrol",
  ["controll{ed,er,ers,ing}"] = "control{ed,er,ers,ing}",
  ["convenience"] = "convience",
  ["convenient"] = "convient",
  ["convert"] = "conevrt",
  ["coordinat{e,es,ed,ing}"] = "coordiant{e,es,ed,ing}",
  ["correct"] = "corerct",
  ["correlation{}"] = "corelation{,s}",
  ["correspondence"] = "correspondance",
  ["could"] = "coudl",
  ["courageous"] = "couragous",
  ["creat{e,es,ed,ing,or,ors}"] = "craet{e,es,ed,ing,or,ors}",
  ["credential{}"] = "credentail{,s}",
  ["criticism"] = "critisism",
  ["crucial"] = "cruical",
  ["curious"] = "curius",
  ["current"] = "currnet",
  ["database"] = "datbase",
  ["daughter"] = "daugther",
  ["deceive"] = "decieve",
  ["decision"] = "descision",
  ["declaration"] = "decleration",
  ["default"] = "defualt",
  ["defer{red,ring}"] = "defer{ed,ing}",
  ["define"] = "defien",
  ["definitely"] = "definetely",
  ["definite{,ly}"] = "definat{e,ely}",
  ["definition{}"] = "defintion{,s}",
  ["delete"] = "delte",
  ["demonstrate"] = "demonstate",
  ["dependency"] = "{depednency,dependnecy}",
  ["designed"] = "desigend",
  ["desperate"] = "desparate",
  ["destination"] = "destinaton",
  ["destroy{}"] = "destory{,s,ed,ing,er,ers}",
  ["destruction"] = "destructon",
  ["detail"] = "detial",
  ["determine"] = "detemrine",
  ["development"] = "developement",
  ["device"] = "deivce",
  ["diagnostic{}"] = "diagnotic{,s}",
  ["dictionary"] = "dictionairy",
  ["difference"] = "diffrence",
  ["different"] = "{diferent,differant,diffrent}",
  ["difficult"] = "{dificult,difficutl}",
  ["dilemma{}"] = "dilema{,s}",
  ["dimension"] = "dimention",
  ["direct"] = "driect",
  ["direction{}"] = "directon{,s}",
  ["directory"] = "{direcotry,driectory}",
  ["disappear{}"] = "dissapear{,s,ed,ing,ance}",
  ["disappointed"] = "dissapointed",
  ["disastrous"] = "disasterous",
  ["discipline"] = "disipline",
  ["discretion{}"] = "discression{,s}",
  ["discussion{}"] = "discusion{,s}",
  ["display"] = "dispaly",
  ["dissatisfied"] = "disatisfied",
  ["distribution{}"] = "distrubution{,s}",
  ["divisible"] = "divisable",
  ["documentation"] = "documention",
  ["does"] = "deos",
  ["duplicate"] = "duplciate",
  ["during"] = "duirng",
  ["dynamic"] = "dyanmic",
  ["d{escription}{}"] = "{desciption,descripton}{,s}",
  ["each"] = "eahc",
  ["ecstasy"] = "ecstacy",
  ["effect"] = "effcet",
  ["efficient"] = "efficent",
  ["eighth"] = "eigth",
  ["either"] = "{eitehr,etiher}",
  ["eligible"] = "eligable",
  ["eliminat{e,es,ed,ing}"] = "elimiat{e,es,ed,ing}",
  ["else"] = "esle",
  ["email"] = "emial",
  ["embarrass{}"] = "embarass{,es,ed,ing,ment}",
  ["embedd{ed,ing}"] = "embed{ed,ing}",
  ["emergency"] = "emergancy",
  ["emphasize"] = "empasize",
  ["enabled"] = "enabeld",
  ["encoding"] = "enconding",
  ["encyclopedia{}"] = "encylopedia{,s}",
  ["engineer{}"] = "enginer{,s,ed,ing}",
  ["enough"] = "enouhg",
  ["ensure"] = "esnure",
  ["enthusiasm"] = "enthusiam",
  ["entirely"] = "entierly",
  ["environment"] = "{environemnt,enviornment,enviroment,envrionment}",
  ["equipment"] = "equiptment",
  ["equivalent"] = "equivilent",
  ["error"] = "erorr",
  ["especially"] = "especialy",
  ["essential"] = "essentail",
  ["evaluate"] = "evalute",
  ["everybody"] = "{everybdoy,everybdy}",
  ["everyday"] = "{everday,everydy}",
  ["everyone"] = "everyoen",
  ["everything"] = "{everyhting,everythign,everyting,everthing}",
  ["everywhere"] = "everyhwere",
  ["exaggerate"] = "exagerate",
  ["example"] = "exmaple",
  ["exceed"] = "excede",
  ["excellent"] = "excelent",
  ["exception"] = "exeption",
  ["exceptional"] = "exeptional",
  ["executable"] = "excutable",
  ["exercise"] = "excercise",
  ["exhilarat{e,es,ed,ing,ion}"] = "exhilerat{e,es,ed,ing,ion}",
  ["existence"] = "existance",
  ["existing"] = "exisitng",
  ["expect"] = "exepct",
  ["experience"] = "experiance",
  ["explanation"] = "explaination",
  ["explicit"] = "expilcit",
  ["explicit{,ly}"] = "{explict,explicitlly}",
  ["extremely"] = "extremly",
  ["e{very}{}"] = "{evey,evrey}{,body,day,one,thing,where}",
  ["familiar"] = "familar",
  ["fascinating"] = "facinating",
  ["feasible"] = "feasable",
  ["feature"] = "fetaure",
  ["february"] = "febuary",
  ["field"] = "feild",
  ["final{,ly}"] = "{fianl,finaly}",
  ["find"] = "fnid",
  ["first"] = "frist",
  ["following"] = "folowing",
  ["foreign"] = "foriegn",
  ["forfeit{}"] = "forefit{,s,ed,ing}",
  ["format"] = "fomrat",
  ["formerly"] = "formely",
  ["forty"] = "fourty",
  ["forward"] = "foward",
  ["found"] = "foudn",
  ["frequently"] = "frequenly",
  ["friend"] = "freind",
  ["fulfill{}"] = "fullfill{,s,ed,ing,ment,ments}",
  ["function"] = "{fucntion,funtion}",
  ["functionality"] = "functionallity",
  ["fundamental"] = "fundemental",
  ["future"] = "futuer",
  ["gauge"] = "guage",
  ["general"] = "genreal",
  ["general{,ly}"] = "{genral,generaly}",
  ["genius"] = "genious",
  ["genuine"] = "genuin",
  ["given"] = "gievn",
  ["global"] = "gloabl",
  ["government"] = "goverment",
  ["grammar"] = "grammer",
  ["grateful"] = "greatful",
  ["great"] = "graet",
  ["grievance{}"] = "greivance{,s}",
  ["group"] = "gruop",
  ["guarantee"] = "{garantee,guarentee}",
  ["guard"] = "gaurd",
  ["guidance"] = "guidence",
  ["handle"] = "hanlde",
  ["happen"] = "happne",
  ["happened"] = "happend",
  ["happen{}"] = "hapen{,s,ed,ing}",
  ["harass{}"] = "harrass{,es,ed,ing,ment}",
  ["have"] = "{ahve,haev,hvae}",
  ["height"] = "heigth",
  ["help"] = "hepl",
  ["helpful"] = "helpfull",
  ["hierarchy"] = "heirarchy",
  ["history"] = "histroy",
  ["however"] = "howveer",
  ["hygiene"] = "hygeine",
  ["identifier"] = "identfiier",
  ["identity"] = "identitiy",
  ["idiosyncrasy"] = "idiosyncracy",
  ["ignore"] = "ignroe",
  ["imagination{}"] = "imaginaton{,s}",
  ["immediately"] = "immediatley",
  ["immediate{,ly}"] = "{immediat,immediatly}",
  ["immunit{y,ies}"] = "imunit{y,ies}",
  ["implementation{}"] = "implimentation{,s}",
  ["import"] = "imoprt",
  ["important"] = "importnat",
  ["incidentally"] = "incidently",
  ["include"] = "incldue",
  ["increase"] = "increaes",
  ["incredible"] = "incrediable",
  ["independent"] = "independant",
  ["indispensable"] = "indispensible",
  ["inevit{able,ably}"] = "inevit{ible,ibly}",
  ["infinite{,ly}"] = "infinate{,ly}",
  ["influence"] = "influance",
  ["information"] = "{infomration,informaiton}",
  ["initial"] = "intial",
  ["initialize"] = "initialze",
  ["innocent"] = "inocent",
  ["inside"] = "indise",
  ["install"] = "isntall",
  ["installation"] = "instalation",
  ["instance"] = "instnace",
  ["instead"] = "instaed",
  ["instruction{}"] = "instrucion{,s}",
  ["integrate"] = "intergrate",
  ["intelligence"] = "inteligence",
  ["interesting"] = "intresting",
  ["interface"] = "interafce",
  ["interrupted"] = "interupted",
  ["interrupt{}"] = "interupt{,s,ed,ing,ion,ions}",
  ["into"] = "itno",
  ["irrelevant"] = "irrelevent",
  ["irresist{ible,ibly}"] = "irresist{able,ably}",
  ["issue"] = "isuse",
  ["iteration{}"] = "iteraton{,s}",
  ["just"] = "jsut",
  ["keyboard"] = "keybaord",
  ["know"] = "{knwo,konw}",
  ["knowledge"] = "knowlege",
  ["laborator{y,ies}"] = "labrator{y,ies}",
  ["language"] = "langauge",
  ["later"] = "laetr",
  ["leave"] = "levae",
  ["leisure"] = "liesure",
  ["length"] = "lenght",
  ["liaison"] = "liason",
  ["library"] = "lib{ary,ray}",
  ["license"] = "lisence",
  ["like"] = "liek",
  ["likely"] = "likley",
  ["little"] = "littel",
  ["local"] = "lcoal",
  ["logical"] = "logcial",
  ["loneliness"] = "lonliness",
  ["long"] = "lnog",
  ["machine"] = "mahcine",
  ["made"] = "maed",
  ["magnificent{,ly}"] = "magnificant{,ly}",
  ["maintenance"] = "maintainance",
  ["mak{e,es,er,ers,ing}"] = "mka{e,es,er,ers,ing}",
  ["manageable"] = "managable",
  ["management"] = "managment",
  ["manually"] = "manualy",
  ["many"] = "mnay",
  ["maximum"] = "maxium",
  ["medieval"] = "mideval",
  ["memory"] = "memroy",
  ["message{}"] = "mesage{,s}",
  ["metadata"] = "meatdata",
  ["method{}"] = "mehtod{,s}",
  ["might"] = "migth",
  ["millennium"] = "millenium",
  ["miniature{}"] = "miniture{,s}",
  ["minimum"] = "minumum",
  ["miscellaneous"] = "{miscelaneous,miscellanous}",
  ["mischievous"] = "mischievious",
  ["misspell{}"] = "mispell{,s,ed,ing}",
  ["model"] = "modle",
  ["modify"] = "modfiy",
  ["module{}"] = "moduel{,s}",
  ["more"] = "moer",
  ["mortgage{}"] = "morgage{,s,d}",
  ["most"] = "msot",
  ["much"] = "mcuh",
  ["multiple"] = "mulitple",
  ["name"] = "naem",
  ["narrative{}"] = "narative{,s}",
  ["natural"] = "natual",
  ["navigation"] = "navagation",
  ["necessary"] = "necesary",
  ["necessar{y,ily}"] = "neccessar{y,ily}",
  ["negligible"] = "negligable",
  ["neighbor"] = "nieghbor",
  ["neither"] = "niether",
  ["never"] = "{neevr,nevre}",
  ["new"] = "nwe",
  ["next"] = "enxt",
  ["ninety"] = "ninty",
  ["normal{,ly}"] = "{norml,normaly}",
  ["noticeable"] = "noticable",
  ["noticeably"] = "noticably",
  ["notification"] = "notifcation",
  ["nuclear"] = "nucular",
  ["number"] = "nubmer",
  ["obedience"] = "obediance",
  ["obvious"] = "obivous",
  ["occasion"] = "occassion",
  ["occasionally"] = "ocassionally",
  ["occur{rence,red,rence}"] = "occur{ance,ed,ence}",
  ["official"] = "offical",
  ["often"] = "ofetn",
  ["omission"] = "ommission",
  ["once"] = "ocne",
  ["one{}"] = "oen{,self}",
  ["only"] = "onyl",
  ["operator"] = "operater",
  ["opportunit{y,ies}"] = "oportunit{y,ies}",
  ["optional"] = "optinal",
  ["option{}"] = "optoin{,s}",
  ["order"] = "ordre",
  ["original{,ly}"] = "{orginal,originaly}",
  ["other"] = "otehr",
  ["package{}"] = "pakcage{,s,d}",
  ["parallel"] = "paralell",
  ["parameter"] = "paramater",
  ["particular"] = "particualr",
  ["pastime{}"] = "passtime{,s}",
  ["pattern{}"] = "patern{,s,ed,ing}",
  ["pavilion{}"] = "pavillion{,s}",
  ["people"] = "peopel",
  ["perceiv{e,es,ed,ing}"] = "percie{ve,ves,ved,ving}",
  ["performance"] = "perfomance",
  ["perhaps"] = "prehaps",
  ["permanent"] = "permanant",
  ["permission"] = "permision",
  ["persistent"] = "persistant",
  ["persuad{e,es,ed,ing}"] = "pursuad{e,es,ed,ing}",
  ["phenomenon"] = "phenomonon",
  ["plac{e,es,ed,ing}"] = "palc{e,es,ed,ing}",
  ["playwright{}"] = "playwrite{,s}",
  ["please"] = "plaese",
  ["plugin"] = "{plguin,pulgin}",
  ["point"] = "poitn",
  ["position"] = "postion",
  ["possession"] = "posession",
  ["possibilit{y,ies}"] = "possibilt{y,ies}",
  ["possible"] = "posible",
  ["potatoes"] = "potatos",
  ["practically"] = "practicaly",
  ["precede"] = "preceed",
  ["precedence"] = "precendence",
  ["preference"] = "preferance",
  ["preferr{ed,ing}"] = "prefer{ed,ing}",
  ["prefer{able,ably}"] = "prefer{ible,ibly}",
  ["preparation"] = "preperation",
  ["presence"] = "presense",
  ["preview"] = "preivew",
  ["previous"] = "prevous",
  ["primary"] = "primayr",
  ["private"] = "priavte",
  ["privilege"] = "priviledge",
  ["probably"] = "probaly",
  ["problem"] = "{probelm,porblem}",
  ["proceed{,s,ed,ing}"] = "procede{,s,d,ing}",
  ["process{}"] = "proccess{,es,ed,ing}",
  ["production"] = "prodcution",
  ["professional"] = "profesional",
  ["professor{}"] = "proffessor{,s}",
  ["project"] = "{proejct,porject}",
  ["promise{}"] = "promisse{,s,d}",
  ["promising"] = "promissing",
  ["pronounc{e,es,ed,ing}"] = "pronouc{e,es,ed,ing}",
  ["pronunciation"] = "pronounciation",
  ["propert{y,ies}"] = "propret{y,ies}",
  ["proposal"] = "proposel",
  ["provide"] = "provdie",
  ["publicly"] = "publically",
  ["purpose"] = "purpsoe",
  ["quantit{y,ies}"] = "quanit{y,ies}",
  ["query"] = "qeury",
  ["question"] = "quesiton",
  ["questionnaire"] = "questionaire",
  ["readable"] = "readible",
  ["really"] = "{raelly,relaly}",
  ["real{,ly}"] = "{rael,realy}",
  ["reason"] = "{reaosn,resaon}",
  ["receive"] = "recieve",
  ["recent"] = "recnet",
  ["recognize"] = "reconize",
  ["recommend{}"] = "recomend{,s,ed,ing,ation}",
  ["recursive"] = "recusive",
  ["reference"] = "{referecne,refrence}",
  ["referr{ed,ing,al}"] = "refer{ed,ing,al}",
  ["relationship"] = "relashionship",
  ["relevant"] = "relevent",
  ["remember"] = "remeber",
  ["remove"] = "reomve",
  ["repetition"] = "repeatition",
  ["replace"] = "relpace",
  ["repository"] = "{repositroy,respository}",
  ["request{}"] = "reqeust{,s,ed,ing}",
  ["require"] = "requrie",
  ["required"] = "requried",
  ["resistance{}"] = "resistence{,s}",
  ["resolution"] = "resoluton",
  ["resource{}"] = "resouce{,s}",
  ["response"] = "repsonse",
  ["response{}"] = "reponse{,s}",
  ["responsibilit{y,ies}"] = "responsabilit{y,ies}",
  ["restaurant"] = "{restaraunt,resturant}",
  ["result"] = "resutl",
  ["retrieve"] = "retreive",
  ["return"] = "reutrn",
  ["rhythm"] = "{rhytm,rythym}",
  ["ridiculous{,ly}"] = "rediculous{,ly}",
  ["right"] = "rigth",
  ["running"] = "runing",
  ["sacrific{e,es,ed,ing}"] = "sacrafic{e,es,ed,ing}",
  ["sacrilegious"] = "sacreligious",
  ["safety"] = "saftey",
  ["said"] = "siad",
  ["same"] = "smae",
  ["schedule"] = "shedule",
  ["secretary"] = "secretery",
  ["section{}"] = "seciton{,s}",
  ["security"] = "securtiy",
  ["sentence"] = "sentance",
  ["separate{}"] = "seperate{,ly}",
  ["sequence"] = "sequnce",
  ["server"] = "srever",
  ["setting"] = "setitng",
  ["several"] = "severl",
  ["should"] = "shoudl",
  ["siege"] = "seige",
  ["significant"] = "signifcant",
  ["similar{}"] = "similiar{,ity,ly}",
  ["simple"] = "simpel",
  ["since"] = "sicne",
  ["sincerely"] = "sincerly",
  ["small"] = "samll",
  ["software"] = "{sofware,sofwtare}",
  ["somebody"] = "{somebdoy,somebdy,sombody}",
  ["someday"] = "somday",
  ["somehow"] = "{somehwo,somhow}",
  ["someone"] = "{someoen,somone}",
  ["someplace"] = "somepalce",
  ["something"] = "{somehting,somethign,somethng,somthing}",
  ["sometime"] = "sometmie",
  ["somewhat"] = "somewaht",
  ["somewhere"] = "somehwere",
  ["sophisticat{e,es,ed,ing}"] = "sophisiticat{e,es,ed,ing}",
  ["source"] = "souce",
  ["specific"] = "specifc",
  ["specifically"] = "specificly",
  ["specify"] = "specifiy",
  ["speech"] = "speach",
  ["standard"] = "standad",
  ["state"] = "staet",
  ["statement"] = "statment",
  ["still"] = "sitll",
  ["strategy"] = "{starategy,stratgey}",
  ["strength"] = "strenght",
  ["string"] = "stirng",
  ["structur{e,es,ed,ing}"] = "strucutr{e,es,ed,ing}",
  ["successful{}"] = "succesful{,ly}",
  ["such"] = "suhc",
  ["sufficient"] = "sufficent",
  ["summary"] = "sumary",
  ["supersede"] = "supercede",
  ["support"] = "supoprt",
  ["surprise"] = "suprise",
  ["surveillance"] = "surveilance",
  ["synchronous"] = "syncronous",
  ["syntax"] = "sytnax",
  ["system"] = "sytem",
  ["s{ome}{}"] = "{smoe,soem}{,body,day,how,one,place,thing,time,what,where}",
  ["tak{e,es,en,ing}"] = "tka{e,es,en,ing}",
  ["technical"] = "tecnical",
  ["technology"] = "technolgy",
  ["temperature"] = "{tempature,temperture}",
  ["templat{e,es,ed,ing}"] = "tempalt{e,es,ed,ing}",
  ["temporary"] = "temperary",
  ["tendency"] = "tendancy",
  ["terminal"] = "temrinal",
  ["testing"] = "testign",
  ["than"] = "thna",
  ["that"] = "taht",
  ["the"] = "{hte,teh}",
  ["their"] = "thier",
  ["themselves"] = "themselfs",
  ["then"] = "tehn",
  ["there"] = "tehre",
  ["these"] = "{htese,tehse}",
  ["they"] = "tehy",
  ["this"] = "{thsi,tihs}",
  ["those"] = "thsoe",
  ["threshold"] = "threshhold",
  ["through"] = "{thorugh,throuhg}",
  ["throughout"] = "througout",
  ["time"] = "tiem",
  ["timeout"] = "timout",
  ["together"] = "{togehter,togther}",
  ["token"] = "toekn",
  ["tomorrow"] = "tommorow",
  ["tragedy"] = "tradgedy",
  ["transfer"] = "tranfer",
  ["transferr{ed,ing}"] = "transfer{ed,ing}",
  ["treatment{}"] = "treatement{,s}",
  ["trigger"] = "triger",
  ["true"] = "ture",
  ["truly"] = "truely",
  ["twelfth"] = "twelth",
  ["typ{e,es,ed,ing}"] = "tpy{e,es,ed,ing}",
  ["tyrann{y,ies}"] = "tyran{y,ies}",
  ["t{hing}{}"] = "{hting,thign,thnig,tihng}{,s}",
  ["t{hink}{}"] = "{htink,thikn,thnik,tihnk}{,ing,s}",
  ["unanimous"] = "unanymous",
  ["under"] = "udner",
  ["understand"] = "understnad",
  ["unforeseen"] = "unforseen",
  ["unfortunate{,ly}"] = "{unfortuante,unfortunatly}",
  ["unique"] = "unqiue",
  ["unknown"] = "{unknwon,unkown}",
  ["unnecessar{y,ily}"] = "unecessar{y,ily}",
  ["until"] = "untill",
  ["unusual"] = "unusal",
  ["update"] = "udpate",
  ["useful"] = "usefull",
  ["using"] = "{uisng,usign}",
  ["usually"] = "usualy",
  ["us{e,es,ed,er,ers,ing}"] = "ues{e,es,ed,er,ers,ing}",
  ["utility"] = "utilty",
  ["vacuum"] = "{vaccum,vacum}",
  ["validate"] = "validte",
  ["value{}"] = "vlaue{,s}",
  ["variable{}"] = "varible{,s}",
  ["various"] = "varous",
  ["vehicle{}"] = "vehical{,s}",
  ["version"] = "verison",
  ["very"] = "vrey",
  ["vicious"] = "visious",
  ["visible"] = "visable",
  ["want"] = "wnat",
  ["warrant{y,ies}"] = "warrent{y,ies}",
  ["was"] = "wsa",
  ["wednesday"] = "wendesday",
  ["weird"] = "wierd",
  ["what"] = "{waht,whta}",
  ["when"] = "wehn",
  ["where"] = "wehre",
  ["which"] = "whcih",
  ["while"] = "wihle",
  ["whole"] = "wohle",
  ["will"] = "{iwll,wlil}",
  ["window"] = "widnow",
  ["with"] = "wtih",
  ["with{}"] = "wiht{,in,out}",
  ["wonderful"] = "wonderfull",
  ["word{}"] = "wrod{,s}",
  ["wore"] = "wroe",
  ["workflow"] = "worklfow",
  ["working"] = "wokring",
  ["work{}"] = "wrok{,s,ed,er,ers,ing}",
  ["world{}"] = "wrold{,s,wide}",
  ["worm{}"] = "wrom{,s,ed,ing}",
  ["worn"] = "wron",
  ["worr{y,ies,ied,ying}"] = "wror{y,ies,ied,ying}",
  ["worship{}"] = "wroship{,s,ed,er,ers,ing}",
  ["wors{e,t}"] = "wros{e,t}",
  ["worthy"] = "wrothy",
  ["would"] = "woudl",
  ["writing"] = "writting",
  ["writ{e,es,er,ers,ing}"] = "wirt{e,es,er,ers,ing}",
  ["writ{e,es}"] = "wrie{t,ts}",
  ["year"] = "yaer",
  ["yield"] = "yeild",
  ["you"] = "yuo",
  ["your"] = "yuor",
}

local function split_alternatives(value)
  local alternatives = {}
  local start = 1

  while true do
    local comma = value:find(",", start, true)
    if not comma then
      table.insert(alternatives, value:sub(start))
      return alternatives
    end

    table.insert(alternatives, value:sub(start, comma - 1))
    start = comma + 1
  end
end

local function brace_parts(value)
  local open = value:find("{", 1, true)
  if not open then
    assert(not value:find("}", 1, true), ("Unmatched } in %q"):format(value))
    return nil
  end

  local close = value:find("}", open + 1, true)
  assert(close, ("Unmatched { in %q"):format(value))
  assert(
    not value:sub(open + 1, close - 1):find("{", 1, true),
    ("Nested braces are not supported in %q"):format(value)
  )

  return value:sub(1, open - 1),
    value:sub(open + 1, close - 1),
    value:sub(close + 1)
end

local function expand_braces(lhs, rhs)
  local expanded = {}
  local pending = { { lhs = lhs, rhs = rhs } }

  while #pending > 0 do
    local entry = table.remove(pending)
    local lhs_before, lhs_middle, lhs_after = brace_parts(entry.lhs)

    if not lhs_before then
      assert(
        not brace_parts(entry.rhs),
        ("Replacement has more brace pairs than %q"):format(lhs)
      )
      expanded[entry.lhs] = entry.rhs
    else
      local targets = split_alternatives(lhs_middle)
      local rhs_before, rhs_middle, rhs_after = brace_parts(entry.rhs)
      local replacements = rhs_middle and split_alternatives(rhs_middle) or nil

      -- An empty replacement pair aliases the corresponding alternatives from
      -- the left-hand side, as in: seperate{,ly} -> separate{}.
      if replacements and #replacements == 1 and replacements[1] == "" then
        replacements = targets
      end

      for index, target in ipairs(targets) do
        local replacement = entry.rhs
        if replacements then
          replacement = rhs_before
            .. replacements[((index - 1) % #replacements) + 1]
            .. rhs_after
        end

        table.insert(pending, {
          lhs = lhs_before .. target .. lhs_after,
          rhs = replacement,
        })
      end
    end
  end

  return expanded
end

local function title_case(word)
  return word:sub(1, 1):upper() .. word:sub(2)
end

local function expand_corrections(entries)
  local expanded = {}

  for correction, variants in pairs(entries) do
    for typo, expanded_correction in pairs(expand_braces(variants, correction)) do
      assert(
        typo ~= expanded_correction,
        ("Correction maps %q to itself"):format(typo)
      )
      assert(
        expanded[typo] == nil or expanded[typo] == expanded_correction,
        ("Conflicting corrections for %q"):format(typo)
      )
      expanded[typo] = expanded_correction
    end
  end

  return expanded
end

local function with_case_variants(entries)
  local variants = {}

  for typo, correction in pairs(entries) do
    variants[typo] = correction
    variants[title_case(typo)] = title_case(correction)
    variants[typo:upper()] = correction:upper()
  end

  return variants
end

local case_aware_corrections =
  with_case_variants(expand_corrections(corrections))

-- Use an allowlist so intentionally unusual identifiers remain untouched in code.
local enabled_filetypes = {
  gitcommit = true,
  markdown = true,
}

local function install(bufnr)
  if vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo, correction in pairs(case_aware_corrections) do
    vim.keymap.set("ia", typo, correction, {
      buffer = bufnr,
      desc = ("Correct %s to %s"):format(typo, correction),
      noremap = true,
    })
  end

  vim.b[bufnr].prose_abbreviations_installed = true
end

local function uninstall(bufnr)
  if not vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo in pairs(case_aware_corrections) do
    vim.keymap.del("ia", typo, { buffer = bufnr })
  end

  vim.b[bufnr].prose_abbreviations_installed = nil
end

function M.setup()
  vim.api.nvim_create_autocmd({ "BufEnter", "FileType" }, {
    group = vim.api.nvim_create_augroup(
      "ProseAbbreviations",
      { clear = true }
    ),
    callback = function(event)
      local enabled = enabled_filetypes[vim.bo[event.buf].filetype] == true
      if enabled then
        install(event.buf)
      else
        uninstall(event.buf)
      end
    end,
  })
end

return M
