local M = {}

-- Keep this list curated: every entry is applied automatically, not suggested,
-- so a typo variant must never be a correctly spelled word.
-- Keys are correct spellings and values are their typo variants. Every key uses
-- the same syntax so the declarations can be sorted lexicographically.
-- Brace alternatives are paired by position. An empty pair on the correct side
-- copies the typo suffixes, so ["separate{}"] = "seperate{,ly}" expands to
-- seperate -> separate and seperately -> separately.
-- Multiple pairs form a product, so ["s{ome}{}"] =
-- "{smoe,soem}{,body}" also covers smoe, soem, smoebody, and soembody.
local corrections = {
  ["abandonment"] = "abandonnment",
  ["abbreviation{}"] = "abreviation{,s}",
  ["ability"] = "abiltiy",
  ["about"] = "{abotu,baout}",
  ["above"] = "abvoe",
  ["absence{}"] = "absense{,s}",
  ["absolutely"] = "absolutley",
  ["abysmal{}"] = "abismal{,ly}",
  ["academic"] = "acadmic",
  ["accelerat{}"] = "acelerat{e,es,ed,ing,ion,ions}",
  ["accept"] = "acecpt",
  ["accepta{}"] = "accepti{ble,bly}",
  ["accessor{}"] = "acessor{y,ies}",
  ["access{}"] = "acess{ible,ibly,ibility}",
  ["accidentally"] = "{accidentaly,accidently}",
  ["accommodat{}"] = "accomodat{e,es,ed,ing,ion,ions}",
  ["according"] = "acording",
  ["accuracy"] = "accuracey",
  ["achiev{}"] = "acheiv{e,es,ed,ing,ement,ements}",
  ["acknowledg{}"] = "acknowleg{e,es,ed,ing,ement,ements}",
  ["acquaintance"] = "{acquaintence,aquaintance}",
  ["acquir{}"] = "aquir{e,es,ed,ing}",
  ["acquisition"] = "aquisition",
  ["across"] = "accross",
  ["action"] = "atcion",
  ["activate"] = "activte",
  ["activit{}"] = "activt{y,ies}",
  ["actual{,ly}"] = "{acutal,actualy}",
  ["additional"] = "additonal",
  ["address{}"] = "adress{,es,ed,ing}",
  ["adequate"] = "adequete",
  ["adjacent"] = "adjecent",
  ["administrator"] = "adminstrator",
  ["adolescence"] = "adolesence",
  ["adolescent{}"] = "adolecent{,s}",
  ["advanced"] = "advnaced",
  ["advantage"] = "advatnage",
  ["advertisement"] = "advertisment",
  ["advice"] = "adivce",
  ["advisable"] = "adviseable",
  ["after"] = "afetr",
  ["again"] = "agian",
  ["against"] = "agianst",
  ["aggressive"] = "agressive",
  ["alcohol"] = "alcohal",
  ["algorithm{}"] = "algorithim{,s}",
  ["allegiance"] = "allegience",
  ["alliance{}"] = "aliance{,s}",
  ["allocat{}"] = "alocat{e,es,ed,ing,ion,ions}",
  ["allotted"] = "alloted",
  ["along"] = "alnog",
  ["already"] = "aleady",
  ["also"] = "aslo",
  ["although"] = "althought",
  ["always"] = "alwasy",
  ["amateur"] = "amature",
  ["amendment{}"] = "ammendment{,s}",
  ["among"] = "amoung",
  ["amount"] = "ammount",
  ["analysis"] = "analisis",
  ["analytically"] = "analyticly",
  ["anniversary"] = "{aniversay,aniversary}",
  ["announcement{}"] = "announcment{,s}",
  ["annual"] = "anual",
  ["anonymous{}"] = "anonymus{,ly}",
  ["another"] = "anohter",
  ["answer"] = "anwser",
  ["anticipat{}"] = "anticiapt{e,es,ed,ing,ion,ions}",
  ["anybody"] = "{anybdoy,anybdy}",
  ["anyhow"] = "anyhwo",
  ["anyone"] = "anyoen",
  ["anyplace"] = "anypalce",
  ["anything"] = "{anyhting,anythign,anyting}",
  ["anytime"] = "anytmie",
  ["anyway"] = "anyawy",
  ["anywhere"] = "anyhwere",
  ["apolog{}"] = "appolog{y,ies}",
  ["apparatus"] = "aparatus",
  ["apparent"] = "apparant",
  ["apparently"] = "{aparently,apparantly}",
  ["appearance{}"] = "appearence{,s}",
  ["appendix"] = "apendix",
  ["application{}"] = "applicaiton{,s}",
  ["appreciat{}"] = "apreciat{e,es,ed,ing,ion,ions}",
  ["appropriate{}"] = "appropiate{,ly}",
  ["approximately"] = "aproximatly",
  ["arbitrary"] = "arbitary",
  ["architecture{}"] = "architechture{,s}",
  ["argument"] = "arugment",
  ["argument{}"] = "arguement{,s}",
  ["around"] = "aroudn",
  ["arrangement{}"] = "arrangment{,s}",
  ["article{}"] = "artilce{,s}",
  ["assassination{}"] = "assasination{,s}",
  ["assignment{}"] = "assigment{,s}",
  ["assistance"] = "assitance",
  ["assistant{}"] = "assitant{,s}",
  ["association{}"] = "assocation{,s}",
  ["asynchronous"] = "asyncronous",
  ["atheist{}"] = "athiest{,s}",
  ["athlet{}"] = "athelet{ic,ics,ically}",
  ["attendance{}"] = "attendence{,s}",
  ["attention{}"] = "attension{,s}",
  ["attribut{}"] = "attrubut{e,es,ed,ing}",
  ["audience{}"] = "audiance{,s}",
  ["author"] = "auhtor",
  ["authorization{}"] = "authorizaton{,s}",
  ["auxiliary"] = "auxillary",
  ["availability"] = "availablity",
  ["available"] = "{avaliable,availble}",
  ["awesome"] = "aweosme",
  ["back"] = "bakc",
  ["background{}"] = "backgroud{,s}",
  ["basic{,ally}"] = "{basci,basicly}",
  ["beautiful"] = "{beautifull,beutiful}",
  ["because"] = "becuase",
  ["become"] = "becmoe",
  ["before"] = "beofre",
  ["beginner{}"] = "beginer{,s}",
  ["beginning"] = "{beggining,begining}",
  ["being"] = "{beign,bieng}",
  ["believe"] = "{beleive,bleiev}",
  ["benefit{}"] = "benifit{,s,ed,ing}",
  ["better"] = "betetr",
  ["between"] = "betwen",
  ["bizarre{}"] = "bizzare{,ly}",
  ["boolean{}"] = "boolen{,s}",
  ["both"] = "btoh",
  ["boundar{}"] = "boundr{y,ies}",
  ["branch{}"] = "brnach{,es}",
  ["brief{}"] = "breif{,s,ly}",
  ["bring{}"] = "birng{,s,ing}",
  ["broccoli"] = "brocoli",
  ["build{}"] = "biuld{,s,ing,er,ers}",
  ["bureaucracy"] = "bureacracy",
  ["b{usiness}{}"] = "{buisness,bussiness}{,es}",
  ["calendar{}"] = "calandar{,s}",
  ["callback{}"] = "calback{,s}",
  ["called"] = "caleld",
  ["camouflag{}"] = "camoflag{e,es,ed,ing}",
  ["candidate{}"] = "canidate{,s}",
  ["capabilit{}"] = "capabilt{y,ies}",
  ["caribbean"] = "carribean",
  ["categor{}"] = "catagor{y,ies}",
  ["cause"] = "casue",
  ["ceiling{}"] = "cieling{,s}",
  ["cemetery"] = "cemetary",
  ["center"] = "cetner",
  ["certain"] = "certian",
  ["certificate{}"] = "certifcate{,s}",
  ["challeng{}"] = "chaleng{e,es,ed,ing}",
  ["change"] = "chagne",
  ["changeable"] = "changable",
  ["chang{}"] = "chnag{e,es,ed,ing}",
  ["characteristic{}"] = "charateristic{,s}",
  ["character{}"] = "charactor{,s}",
  ["check{}"] = "cehck{,s,ed,ing}",
  ["children"] = "chidlren",
  ["choice"] = "chioce",
  ["choose"] = "chosse",
  ["circuit{}"] = "circut{,s}",
  ["clear{}"] = "claer{,s,ed,ing}",
  ["clos{}"] = "clso{e,es,ed,ing}",
  ["cod{}"] = "cdo{e,es,ed,ing}",
  ["cohere{}"] = "cohera{nt,ntly}",
  ["colleague{}"] = "collegue{,s}",
  ["column{}"] = "colum{,s}",
  ["combination{}"] = "combinaton{,s}",
  ["coming"] = "comming",
  ["command"] = "commnad",
  ["command{}"] = "comand{,s,ed,ing}",
  ["commercial{}"] = "comercial{,s}",
  ["commission{}"] = "comission{,s,ed,ing}",
  ["commitment{}"] = "comitment{,s}",
  ["committee"] = "comittee",
  ["committ{}"] = "commit{ed,ing}",
  ["common"] = "comon",
  ["communication{}"] = "communciation{,s}",
  ["communit{}"] = "comunit{y,ies}",
  ["comparative{}"] = "comparitive{,s,ly}",
  ["comparison"] = "comparision",
  ["compatibilit{}"] = "compatabilit{y,ies}",
  ["competition{}"] = "competion{,s}",
  ["completely"] = "completly",
  ["complet{}"] = "comlpet{e,es,ed,ing}",
  ["component"] = "compnoent",
  ["component{}"] = "componet{,s}",
  ["conced{e,es,ed,ing}"] = "conceed{,s,ed,ing}",
  ["conceiv{}"] = "conciev{e,es,ed,ing,able,ably}",
  ["conclusion{}"] = "conclussion{,s}",
  ["concurrenc{}"] = "concurenc{y,ies}",
  ["condition{}"] = "conditon{,s,ed,ing}",
  ["confidence"] = "confidance",
  ["configuration{}"] = "configuraiton{,s}",
  ["configuratio{}"] = "configruatio{n,ns}",
  ["confirmation{}"] = "confirmaton{,s}",
  ["congratulations"] = "congradulations",
  ["connection{}"] = "conection{,s}",
  ["connectio{}"] = "conenctio{n,ns}",
  ["connoisseur{}"] = "conoisseur{,s}",
  ["conscientious"] = "concientious",
  ["conscious{}"] = "concious{,ly}",
  ["consensus{}"] = "concensus{,es}",
  ["consequence{}"] = "consequnce{,s}",
  ["considerable"] = "considerible",
  ["consider{}"] = "consdier{,s,ed,ing,ation,ations}",
  ["consistent{}"] = "consistant{,ly}",
  ["contain{}"] = "contian{,s,ed,ing,er,ers,ment}",
  ["content{}"] = "contnet{,s}",
  ["context"] = "{conetxt,cotnext}",
  ["continuous"] = "continous",
  ["continu{}"] = "continut{e,es,ed,ing,ation,ations}",
  ["control"] = "cotnrol",
  ["controll{}"] = "control{ed,er,ers,ing}",
  ["convenience{}"] = "convience{,s}",
  ["convenient{}"] = "convient{,ly}",
  ["convert"] = "conevrt",
  ["coordinat{}"] = "coordiant{e,es,ed,ing}",
  ["correct{}"] = "corerct{,s,ed,ing,ion,ions,ly}",
  ["correlation{}"] = "corelation{,s}",
  ["correspondence{}"] = "correspondance{,s}",
  ["could"] = "coudl",
  ["counterfeit{}"] = "counterfit{,s,ed,ing,er,ers}",
  ["courageous"] = "couragous",
  ["creat{}"] = "craet{e,es,ed,ing,or,ors}",
  ["credential{}"] = "credentail{,s}",
  ["criticism{}"] = "critisism{,s}",
  ["crucial"] = "cruical",
  ["curious{}"] = "curius{,ly}",
  ["current{}"] = "currnet{,ly}",
  ["database{}"] = "datbase{,s}",
  ["daughter"] = "daugther",
  ["deallocat{}"] = "dealocat{e,es,ed,ing,ion,ions}",
  ["deceiv{}"] = "deciev{e,es,ed,ing}",
  ["decision{}"] = "descision{,s}",
  ["declaration{}"] = "decleration{,s}",
  ["default{}"] = "defualt{,s,ed,ing}",
  ["deferr{}"] = "defer{ed,ing}",
  ["definitely"] = "definetely",
  ["definite{}"] = "definate{,ly}",
  ["definition{}"] = "defintion{,s}",
  ["defin{e,es,ed,ing}"] = "defien{,s,ed,ing}",
  ["delete"] = "delte",
  ["delimiter{}"] = "delimeter{,s}",
  ["demonstrat{}"] = "demonstat{e,es,ed,ing,ion,ions}",
  ["dependency"] = "{depednency,dependnecy}",
  ["deprecat{}"] = "depreceat{e,es,ed,ing,ion,ions}",
  ["designed"] = "desigend",
  ["desperate{}"] = "desparate{,ly}",
  ["destination{}"] = "destinaton{,s}",
  ["destroy{}"] = "destory{,s,ed,ing,er,ers}",
  ["destruction{}"] = "destructon{,s}",
  ["detail{}"] = "detial{,s}",
  ["determine"] = "detemrine",
  ["development{}"] = "developement{,s}",
  ["device{}"] = "deivce{,s}",
  ["diagnostic{}"] = "diagnotic{,s}",
  ["dictionar{}"] = "dictionair{y,ies}",
  ["difference{}"] = "diffrence{,s}",
  ["different"] = "{diferent,differant,diffrent}",
  ["difficult"] = "difficutl",
  ["difficul{}"] = "dificul{t,ty,ties}",
  ["dilemma{}"] = "dilema{,s}",
  ["dimension{}"] = "dimention{,s}",
  ["direct"] = "driect",
  ["direction{}"] = "directon{,s}",
  ["directory"] = "{direcotry,driectory}",
  ["disappear{}"] = "dissapear{,s,ed,ing,ance}",
  ["disappointed"] = "dissapointed",
  ["disastrous"] = "disasterous",
  ["disciplin{}"] = "disiplin{e,es,ed,ing}",
  ["discretion{}"] = "discression{,s}",
  ["discussion{}"] = "discusion{,s}",
  ["display{}"] = "dispaly{,s,ed,ing}",
  ["dissatisfied"] = "disatisfied",
  ["distribution{}"] = "distrubution{,s}",
  ["divisible"] = "divisable",
  ["documentation"] = "documention",
  ["does"] = "deos",
  ["drunkenness"] = "drunkeness",
  ["dumbbell{}"] = "dumbell{,s}",
  ["duplicat{}"] = "duplciat{e,es,ed,ing}",
  ["during"] = "duirng",
  ["dynamic"] = "dyanmic",
  ["d{escription}{}"] = "{desciption,descripton}{,s}",
  ["each"] = "eahc",
  ["ecclesiastical{}"] = "eclesiastical{,ly}",
  ["ecstasy"] = "ecstacy",
  ["effect"] = "effcet",
  ["efficient"] = "efficent",
  ["eighth"] = "eigth",
  ["either"] = "{eitehr,etiher}",
  ["eligible"] = "eligable",
  ["eliminat{}"] = "elimiat{e,es,ed,ing}",
  ["else"] = "esle",
  ["email"] = "emial",
  ["embarrass{}"] = "embarass{,es,ed,ing,ment}",
  ["embedd{}"] = "embed{ed,ing}",
  ["emergency"] = "emergancy",
  ["emphasize"] = "empasize",
  ["enabled"] = "enabeld",
  ["encoding"] = "enconding",
  ["encyclopedia{}"] = "encylopedia{,s}",
  ["engineer{}"] = "enginer{,s,ed,ing}",
  ["enough"] = "enouhg",
  ["ensure"] = "esnure",
  ["enthusiasm"] = "enthusiam",
  ["entirely"] = "entierly",
  ["environment"] = "{environemnt,enviornment,enviroment,envrionment}",
  ["equipment"] = "equiptment",
  ["equivalent"] = "equivilent",
  ["error"] = "erorr",
  ["especially"] = "especialy",
  ["essential"] = "essentail",
  ["evaluate"] = "evalute",
  ["everybody"] = "{everybdoy,everybdy}",
  ["everyday"] = "{everday,everydy}",
  ["everyone"] = "everyoen",
  ["everything"] = "{everyhting,everythign,everyting,everthing}",
  ["everywhere"] = "everyhwere",
  ["exaggerate"] = "exagerate",
  ["example"] = "exmaple",
  ["exceed"] = "excede",
  ["excellent"] = "excelent",
  ["exception"] = "exeption",
  ["exceptional"] = "exeptional",
  ["executable"] = "excutable",
  ["execution{}"] = "excution{,s}",
  ["exercise"] = "excercise",
  ["exhilarat{}"] = "exhilerat{e,es,ed,ing,ion}",
  ["existence"] = "existance",
  ["existing"] = "exisitng",
  ["expect"] = "exepct",
  ["experience"] = "experiance",
  ["explanation"] = "explaination",
  ["explicit"] = "expilcit",
  ["explicit{,ly}"] = "{explict,explicitlly}",
  ["extremely"] = "extremly",
  ["e{very}{}"] = "{evey,evrey}{,body,day,one,thing,where}",
  ["fahrenheit"] = "farenheit",
  ["familiar"] = "familar",
  ["fascinating"] = "facinating",
  ["feasible"] = "feasable",
  ["feature"] = "fetaure",
  ["february"] = "febuary",
  ["field"] = "feild",
  ["final{,ly}"] = "{fianl,finaly}",
  ["find"] = "fnid",
  ["first"] = "frist",
  ["following"] = "folowing",
  ["foreign"] = "foriegn",
  ["forfeit{}"] = "forefit{,s,ed,ing}",
  ["format"] = "fomrat",
  ["formerly"] = "formely",
  ["forty"] = "fourty",
  ["forward"] = "foward",
  ["found"] = "foudn",
  ["frequently"] = "frequenly",
  ["friend"] = "freind",
  ["fuchsia"] = "fuschia",
  ["fulfill{}"] = "fullfill{,s,ed,ing,ment,ments}",
  ["function"] = "{fucntion,funtion}",
  ["functionality"] = "functionallity",
  ["fundamental"] = "fundemental",
  ["future"] = "futuer",
  ["gauge"] = "guage",
  ["genealog{}"] = "geneolog{y,ies}",
  ["general"] = "genreal",
  ["general{,ly}"] = "{genral,generaly}",
  ["genius"] = "genious",
  ["genuine"] = "genuin",
  ["given"] = "gievn",
  ["global"] = "gloabl",
  ["government"] = "goverment",
  ["grammar"] = "grammer",
  ["grateful"] = "greatful",
  ["great"] = "graet",
  ["grievance{}"] = "greivance{,s}",
  ["group"] = "gruop",
  ["guarantee"] = "{garantee,guarentee}",
  ["guard"] = "gaurd",
  ["guidance"] = "guidence",
  ["handkerchief{}"] = "hankerchief{,s}",
  ["handle"] = "hanlde",
  ["happen"] = "happne",
  ["happened"] = "happend",
  ["happen{}"] = "hapen{,s,ed,ing}",
  ["harass{}"] = "harrass{,es,ed,ing,ment}",
  ["have"] = "{ahve,haev,hvae}",
  ["height"] = "heigth",
  ["help"] = "hepl",
  ["helpful"] = "helpfull",
  ["hierarch{}"] = "heirarch{y,ies,ical,ically}",
  ["history"] = "histroy",
  ["however"] = "howveer",
  ["hygiene"] = "hygeine",
  ["hypocris{}"] = "hipocris{y,ies}",
  ["identifier"] = "identfiier",
  ["identity"] = "identitiy",
  ["idiosyncrasy"] = "idiosyncracy",
  ["ignore"] = "ignroe",
  ["imagination{}"] = "imaginaton{,s}",
  ["immediately"] = "immediatley",
  ["immediate{}"] = "immediat{,ly}",
  ["immunit{}"] = "imunit{y,ies}",
  ["implementation{}"] = "implimentation{,s}",
  ["import"] = "imoprt",
  ["important"] = "importnat",
  ["incidentally"] = "incidently",
  ["include"] = "incldue",
  ["increase"] = "increaes",
  ["incredible"] = "incrediable",
  ["independent"] = "independant",
  ["indictment{}"] = "inditement{,s}",
  ["indispensable"] = "indispensible",
  ["inevita{}"] = "ineviti{ble,bly}",
  ["infinite{}"] = "infinate{,ly}",
  ["influence"] = "influance",
  ["information"] = "{infomration,informaiton}",
  ["initial"] = "intial",
  ["initialization{}"] = "initilization{,s}",
  ["initialize"] = "initialze",
  ["innocent"] = "inocent",
  ["inside"] = "indise",
  ["install"] = "isntall",
  ["installation"] = "instalation",
  ["instance"] = "instnace",
  ["instead"] = "instaed",
  ["instruction{}"] = "instrucion{,s}",
  ["integer{}"] = "interger{,s}",
  ["integrate"] = "intergrate",
  ["intelligence"] = "inteligence",
  ["interesting"] = "intresting",
  ["interface"] = "interafce",
  ["interpreter{}"] = "interpretter{,s}",
  ["interrupted"] = "interupted",
  ["interrupt{}"] = "interupt{,s,ed,ing,ion,ions}",
  ["into"] = "itno",
  ["irrelevant"] = "irrelevent",
  ["irresisti{}"] = "irresista{ble,bly}",
  ["issue"] = "isuse",
  ["iteration{}"] = "iteraton{,s}",
  ["just"] = "jsut",
  ["keyboard"] = "keybaord",
  ["know"] = "{knwo,konw}",
  ["knowledge"] = "knowlege",
  ["laborator{}"] = "labrator{y,ies}",
  ["language"] = "langauge",
  ["latenc{}"] = "latanc{y,ies}",
  ["later"] = "laetr",
  ["leave"] = "levae",
  ["leisure"] = "liesure",
  ["length"] = "lenght",
  ["lethal{}"] = "leathal{,ly}",
  ["liaison"] = "liason",
  ["library"] = "lib{ary,ray}",
  ["license"] = "lisence",
  ["like"] = "liek",
  ["likely"] = "likley",
  ["little"] = "littel",
  ["local"] = "lcoal",
  ["logical"] = "logcial",
  ["loneliness"] = "lonliness",
  ["long"] = "lnog",
  ["machine"] = "mahcine",
  ["made"] = "maed",
  ["magnificent{}"] = "magnificant{,ly}",
  ["maintenance"] = "maintainance",
  ["mak{}"] = "mka{e,es,er,ers,ing}",
  ["manageable"] = "managable",
  ["management"] = "managment",
  ["manually"] = "manualy",
  ["many"] = "mnay",
  ["mathematics"] = "mathmatics",
  ["maximum"] = "maxium",
  ["medicine{}"] = "medecine{,s}",
  ["medieval"] = "mideval",
  ["memory"] = "memroy",
  ["message{}"] = "mesage{,s}",
  ["metadata"] = "meatdata",
  ["method{}"] = "mehtod{,s}",
  ["might"] = "migth",
  ["millennium"] = "millenium",
  ["miniature{}"] = "miniture{,s}",
  ["minimum"] = "minumum",
  ["miscellaneous"] = "{miscelaneous,miscellanous}",
  ["mischievous"] = "mischievious",
  ["missile{}"] = "missle{,s}",
  ["misspell{}"] = "mispell{,s,ed,ing}",
  ["model"] = "modle",
  ["modify"] = "modfiy",
  ["module{}"] = "moduel{,s}",
  ["monaster{}"] = "monestar{y,ies}",
  ["more"] = "moer",
  ["mortgage{}"] = "morgage{,s,d}",
  ["most"] = "msot",
  ["much"] = "mcuh",
  ["multiple"] = "mulitple",
  ["name"] = "naem",
  ["narrative{}"] = "narative{,s}",
  ["natural"] = "natual",
  ["navigation"] = "navagation",
  ["necessary"] = "necesary",
  ["necessar{}"] = "neccessar{y,ily}",
  ["negligible"] = "negligable",
  ["neighbor"] = "nieghbor",
  ["neither"] = "niether",
  ["never"] = "{neevr,nevre}",
  ["new"] = "nwe",
  ["next"] = "enxt",
  ["ninety"] = "ninty",
  ["normal{,ly}"] = "{norml,normaly}",
  ["noticeable"] = "noticable",
  ["noticeably"] = "noticably",
  ["notification"] = "notifcation",
  ["nuclear"] = "nucular",
  ["number"] = "nubmer",
  ["obedience"] = "obediance",
  ["obvious"] = "obivous",
  ["occasion"] = "occassion",
  ["occasionally"] = "ocassionally",
  ["occurrence{}"] = "occurance{,s}",
  ["occurrenc{}"] = "occurenc{e,es}",
  ["occurre{}"] = "occurra{nce,nces}",
  ["occurr{}"] = "occur{ed,ing}",
  ["official"] = "offical",
  ["often"] = "ofetn",
  ["omission"] = "ommission",
  ["once"] = "ocne",
  ["one{}"] = "oen{,self}",
  ["only"] = "onyl",
  ["operator"] = "operater",
  ["opportunit{}"] = "oportunit{y,ies}",
  ["optional"] = "optinal",
  ["option{}"] = "optoin{,s}",
  ["order"] = "ordre",
  ["original{,ly}"] = "{orginal,originaly}",
  ["other"] = "otehr",
  ["overrid{}"] = "overid{e,es,ing}",
  ["package{}"] = "pakcage{,s,d}",
  ["parallel"] = "paralell",
  ["parameter"] = "paramater",
  ["particular"] = "particualr",
  ["pastime{}"] = "passtime{,s}",
  ["pattern{}"] = "patern{,s,ed,ing}",
  ["pavilion{}"] = "pavillion{,s}",
  ["people"] = "peopel",
  ["perceiv{}"] = "perciev{e,es,ed,ing}",
  ["performance"] = "perfomance",
  ["perhaps"] = "prehaps",
  ["permanent"] = "permanant",
  ["permission"] = "permision",
  ["persistence"] = "persistance",
  ["persistent"] = "persistant",
  ["persuad{}"] = "pursuad{e,es,ed,ing}",
  ["pharaoh{}"] = "pharoah{,s}",
  ["phenomenon"] = "phenomonon",
  ["piece{}"] = "peice{,s}",
  ["pigeon{}"] = "pidgeon{,s}",
  ["plac{}"] = "palc{e,es,ed,ing}",
  ["playwright{}"] = "playwrite{,s}",
  ["pleasant{}"] = "pleasent{,ly}",
  ["please"] = "plaese",
  ["plugin"] = "{plguin,pulgin}",
  ["point"] = "poitn",
  ["politician{}"] = "politican{,s}",
  ["position"] = "postion",
  ["possession"] = "posession",
  ["possibilit{}"] = "possibilt{y,ies}",
  ["possible"] = "posible",
  ["potatoes"] = "potatos",
  ["practically"] = "practicaly",
  ["precede"] = "preceed",
  ["precedence"] = "precendence",
  ["prefera{}"] = "preferi{ble,bly}",
  ["preference"] = "preferance",
  ["preferr{}"] = "prefer{ed,ing}",
  ["preparation"] = "preperation",
  ["presence"] = "presense",
  ["preview"] = "preivew",
  ["previous"] = "prevous",
  ["primary"] = "primayr",
  ["private"] = "priavte",
  ["privilege"] = "priviledge",
  ["probably"] = "probaly",
  ["problem"] = "{probelm,porblem}",
  ["proceed{,s,ed,ing}"] = "procede{,s,d,ing}",
  ["process{}"] = "proccess{,es,ed,ing}",
  ["production"] = "prodcution",
  ["professional"] = "profesional",
  ["professor{}"] = "proffessor{,s}",
  ["project"] = "{proejct,porject}",
  ["promise{}"] = "promisse{,s,d}",
  ["promising"] = "promissing",
  ["pronounc{}"] = "pronouc{e,es,ed,ing}",
  ["pronunciation"] = "pronounciation",
  ["propagat{}"] = "propogat{e,es,ed,ing,ion,ions}",
  ["propert{}"] = "propret{y,ies}",
  ["proposal"] = "proposel",
  ["protocol{}"] = "protocal{,s}",
  ["provide"] = "provdie",
  ["publicly"] = "publically",
  ["purpose"] = "purpsoe",
  ["quantit{}"] = "quanit{y,ies}",
  ["query"] = "qeury",
  ["question"] = "quesiton",
  ["questionnaire"] = "questionaire",
  ["readable"] = "readible",
  ["really"] = "{raelly,relaly}",
  ["real{,ly}"] = "{rael,realy}",
  ["reason"] = "{reaosn,resaon}",
  ["receive"] = "recieve",
  ["recent"] = "recnet",
  ["recognize"] = "reconize",
  ["recommend{}"] = "recomend{,s,ed,ing,ation}",
  ["recursive"] = "recusive",
  ["reference"] = "{referecne,refrence}",
  ["referr{}"] = "refer{ed,ing,al}",
  ["refrigerator{}"] = "refridgerator{,s}",
  ["relationship"] = "relashionship",
  ["relevant"] = "relevent",
  ["religious{}"] = "religous{,ly}",
  ["remember"] = "remeber",
  ["remembrance{}"] = "rememberance{,s}",
  ["remove"] = "reomve",
  ["renderer{}"] = "renderor{,s}",
  ["repetition"] = "repeatition",
  ["replace"] = "relpace",
  ["repository"] = "{repositroy,respository}",
  ["request{}"] = "reqeust{,s,ed,ing}",
  ["require"] = "requrie",
  ["required"] = "requried",
  ["resistance{}"] = "resistence{,s}",
  ["resolution"] = "resoluton",
  ["resource{}"] = "resouce{,s}",
  ["response"] = "repsonse",
  ["response{}"] = "reponse{,s}",
  ["responsibilit{}"] = "responsabilit{y,ies}",
  ["restaurant"] = "{restaraunt,resturant}",
  ["result"] = "resutl",
  ["retrieve"] = "retreive",
  ["return"] = "reutrn",
  ["rhythm"] = "{rhytm,rythym}",
  ["ridiculous{}"] = "rediculous{,ly}",
  ["right"] = "rigth",
  ["running"] = "runing",
  ["sacrific{}"] = "sacrafic{e,es,ed,ing}",
  ["sacrilegious"] = "sacreligious",
  ["safety"] = "saftey",
  ["said"] = "siad",
  ["same"] = "smae",
  ["sandwich{}"] = "sandwhich{,es}",
  ["schedule"] = "shedule",
  ["scissors"] = "sissors",
  ["screenshot{}"] = "screensot{,s}",
  ["secretary"] = "secretery",
  ["section{}"] = "seciton{,s}",
  ["security"] = "securtiy",
  ["sentence"] = "sentance",
  ["separate{}"] = "seperate{,ly}",
  ["sequence"] = "sequnce",
  ["server"] = "srever",
  ["setting"] = "setitng",
  ["several"] = "severl",
  ["should"] = "shoudl",
  ["siege"] = "seige",
  ["significant"] = "signifcant",
  ["similar{}"] = "similiar{,ity,ly}",
  ["simple"] = "simpel",
  ["since"] = "sicne",
  ["sincerely"] = "sincerly",
  ["small"] = "samll",
  ["software"] = "{sofware,sofwtare}",
  ["somebody"] = "{somebdoy,somebdy,sombody}",
  ["someday"] = "somday",
  ["somehow"] = "{somehwo,somhow}",
  ["someone"] = "{someoen,somone}",
  ["someplace"] = "somepalce",
  ["something"] = "{somehting,somethign,somethng,somthing}",
  ["sometime"] = "sometmie",
  ["somewhat"] = "somewaht",
  ["somewhere"] = "somehwere",
  ["sophisticat{}"] = "sophisiticat{e,es,ed,ing}",
  ["source"] = "souce",
  ["souvenir{}"] = "souvenier{,s}",
  ["specific"] = "specifc",
  ["specifically"] = "specificly",
  ["specify"] = "specifiy",
  ["speech"] = "speach",
  ["standard"] = "standad",
  ["state"] = "staet",
  ["statement"] = "statment",
  ["still"] = "sitll",
  ["strategy"] = "{starategy,stratgey}",
  ["strength"] = "strenght",
  ["string"] = "stirng",
  ["structur{}"] = "strucutr{e,es,ed,ing}",
  ["subclass{}"] = "sublcass{,es}",
  ["subprocess{}"] = "subproccess{,es}",
  ["successful{}"] = "succesful{,ly}",
  ["such"] = "suhc",
  ["sufficient"] = "sufficent",
  ["summary"] = "sumary",
  ["supersede"] = "supercede",
  ["support"] = "supoprt",
  ["surprise"] = "suprise",
  ["surveillance"] = "surveilance",
  ["synchronous"] = "syncronous",
  ["syntax"] = "sytnax",
  ["system"] = "sytem",
  ["s{ome}{}"] = "{smoe,soem}{,body,day,how,one,place,thing,time,what,where}",
  ["tak{}"] = "tka{e,es,en,ing}",
  ["technical"] = "tecnical",
  ["technology"] = "technolgy",
  ["temperature"] = "{tempature,temperture}",
  ["templat{}"] = "tempalt{e,es,ed,ing}",
  ["temporary"] = "temperary",
  ["tendency"] = "tendancy",
  ["terminal"] = "temrinal",
  ["testing"] = "testign",
  ["than"] = "thna",
  ["that"] = "taht",
  ["the"] = "{hte,teh}",
  ["their"] = "thier",
  ["themselves"] = "themselfs",
  ["then"] = "tehn",
  ["there"] = "tehre",
  ["these"] = "{htese,tehse}",
  ["they"] = "tehy",
  ["this"] = "{thsi,tihs}",
  ["those"] = "thsoe",
  ["threshold"] = "threshhold",
  ["through"] = "{thorugh,throuhg}",
  ["throughout"] = "througout",
  ["time"] = "tiem",
  ["timeout"] = "timout",
  ["together"] = "{togehter,togther}",
  ["token"] = "toekn",
  ["tomorrow"] = "tommorow",
  ["tournament{}"] = "tournement{,s}",
  ["tragedy"] = "tradgedy",
  ["transfer"] = "tranfer",
  ["transferr{}"] = "transfer{ed,ing}",
  ["treatment{}"] = "treatement{,s}",
  ["trigger"] = "triger",
  ["true"] = "ture",
  ["truly"] = "truely",
  ["twelfth"] = "twelth",
  ["typ{}"] = "tpy{e,es,ed,ing}",
  ["tyrann{}"] = "tyran{y,ies}",
  ["t{hing}{}"] = "{hting,thign,thnig,tihng}{,s}",
  ["t{hink}{}"] = "{htink,thikn,thnik,tihnk}{,ing,s}",
  ["unanimous"] = "unanymous",
  ["under"] = "udner",
  ["understand"] = "understnad",
  ["unforeseen"] = "unforseen",
  ["unfortunate{,ly}"] = "{unfortuante,unfortunatly}",
  ["unique"] = "unqiue",
  ["unknown"] = "{unknwon,unkown}",
  ["unnecessar{}"] = "unecessar{y,ily}",
  ["until"] = "untill",
  ["unusual"] = "unusal",
  ["update"] = "udpate",
  ["useful"] = "usefull",
  ["using"] = "{uisng,usign}",
  ["usually"] = "usualy",
  ["us{}"] = "ues{e,es,ed,er,ers,ing}",
  ["utility"] = "utilty",
  ["vacuum"] = "{vaccum,vacum}",
  ["validate"] = "validte",
  ["value{}"] = "vlaue{,s}",
  ["variable{}"] = "varible{,s}",
  ["various"] = "varous",
  ["vegetable{}"] = "vegtable{,s}",
  ["vehicle{}"] = "vehical{,s}",
  ["version"] = "verison",
  ["very"] = "vrey",
  ["vicious"] = "visious",
  ["villain{}"] = "villian{,s}",
  ["visible"] = "visable",
  ["want"] = "wnat",
  ["warrant{}"] = "warrent{y,ies}",
  ["was"] = "wsa",
  ["wednesday"] = "wendesday",
  ["weird"] = "wierd",
  ["what"] = "{waht,whta}",
  ["when"] = "wehn",
  ["where"] = "wehre",
  ["which"] = "whcih",
  ["while"] = "wihle",
  ["whole"] = "wohle",
  ["will"] = "{iwll,wlil}",
  ["window"] = "widnow",
  ["with"] = "wtih",
  ["with{}"] = "wiht{,in,out}",
  ["wonderful"] = "wonderfull",
  ["word{}"] = "wrod{,s}",
  ["wore"] = "wroe",
  ["workflow"] = "worklfow",
  ["working"] = "wokring",
  ["work{}"] = "wrok{,s,ed,er,ers,ing}",
  ["world{}"] = "wrold{,s,wide}",
  ["worm{}"] = "wrom{,s,ed,ing}",
  ["worn"] = "wron",
  ["worr{}"] = "wror{y,ies,ied,ying}",
  ["worship{}"] = "wroship{,s,ed,er,ers,ing}",
  ["wors{}"] = "wros{e,t}",
  ["worthy"] = "wrothy",
  ["would"] = "woudl",
  ["write{}"] = "wriet{,s}",
  ["writing"] = "writting",
  ["writ{}"] = "wirt{e,es,er,ers,ing}",
  ["yacht{}"] = "yatch{,s}",
  ["year"] = "yaer",
  ["yield"] = "yeild",
  ["you"] = "yuo",
  ["your"] = "yuor",
  ["zealous{}"] = "zelous{,ly}",
}

local function split_alternatives(value)
  local alternatives = {}
  local start = 1

  while true do
    local comma = value:find(",", start, true)
    if not comma then
      table.insert(alternatives, value:sub(start))
      return alternatives
    end

    table.insert(alternatives, value:sub(start, comma - 1))
    start = comma + 1
  end
end

local function brace_parts(value)
  local open = value:find("{", 1, true)
  if not open then
    assert(not value:find("}", 1, true), ("Unmatched } in %q"):format(value))
    return nil
  end

  local close = value:find("}", open + 1, true)
  assert(close, ("Unmatched { in %q"):format(value))
  assert(
    not value:sub(open + 1, close - 1):find("{", 1, true),
    ("Nested braces are not supported in %q"):format(value)
  )

  return value:sub(1, open - 1),
    value:sub(open + 1, close - 1),
    value:sub(close + 1)
end

local function expand_braces(lhs, rhs)
  local expanded = {}
  local pending = { { lhs = lhs, rhs = rhs } }

  while #pending > 0 do
    local entry = table.remove(pending)
    local lhs_before, lhs_middle, lhs_after = brace_parts(entry.lhs)

    if not lhs_before then
      assert(
        not brace_parts(entry.rhs),
        ("Replacement has more brace pairs than %q"):format(lhs)
      )
      expanded[entry.lhs] = entry.rhs
    else
      local targets = split_alternatives(lhs_middle)
      local rhs_before, rhs_middle, rhs_after = brace_parts(entry.rhs)
      local replacements = rhs_middle and split_alternatives(rhs_middle) or nil

      -- An empty replacement pair aliases the corresponding alternatives from
      -- the left-hand side, as in: seperate{,ly} -> separate{}.
      if replacements and #replacements == 1 and replacements[1] == "" then
        replacements = targets
      end

      for index, target in ipairs(targets) do
        local replacement = entry.rhs
        if replacements then
          replacement = rhs_before
            .. replacements[((index - 1) % #replacements) + 1]
            .. rhs_after
        end

        table.insert(pending, {
          lhs = lhs_before .. target .. lhs_after,
          rhs = replacement,
        })
      end
    end
  end

  return expanded
end

local function title_case(word)
  return word:sub(1, 1):upper() .. word:sub(2)
end

local function expand_corrections(entries)
  local expanded = {}

  for correction, variants in pairs(entries) do
    for typo, expanded_correction in pairs(expand_braces(variants, correction)) do
      assert(
        typo ~= expanded_correction,
        ("Correction maps %q to itself"):format(typo)
      )
      assert(
        expanded[typo] == nil or expanded[typo] == expanded_correction,
        ("Conflicting corrections for %q"):format(typo)
      )
      expanded[typo] = expanded_correction
    end
  end

  return expanded
end

local function with_case_variants(entries)
  local variants = {}

  for typo, correction in pairs(entries) do
    variants[typo] = correction
    variants[title_case(typo)] = title_case(correction)
    variants[typo:upper()] = correction:upper()
  end

  return variants
end

local case_aware_corrections =
  with_case_variants(expand_corrections(corrections))

-- Use an allowlist so intentionally unusual identifiers remain untouched in code.
local enabled_filetypes = {
  gitcommit = true,
  markdown = true,
}

local function install(bufnr)
  if vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo, correction in pairs(case_aware_corrections) do
    vim.keymap.set("ia", typo, correction, {
      buffer = bufnr,
      desc = ("Correct %s to %s"):format(typo, correction),
      noremap = true,
    })
  end

  vim.b[bufnr].prose_abbreviations_installed = true
end

local function uninstall(bufnr)
  if not vim.b[bufnr].prose_abbreviations_installed then
    return
  end

  for typo in pairs(case_aware_corrections) do
    vim.keymap.del("ia", typo, { buffer = bufnr })
  end

  vim.b[bufnr].prose_abbreviations_installed = nil
end

function M.setup()
  vim.api.nvim_create_autocmd({ "BufEnter", "FileType" }, {
    group = vim.api.nvim_create_augroup(
      "ProseAbbreviations",
      { clear = true }
    ),
    callback = function(event)
      local enabled = enabled_filetypes[vim.bo[event.buf].filetype] == true
      if enabled then
        install(event.buf)
      else
        uninstall(event.buf)
      end
    end,
  })
end

return M
