[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
enable_error_code = ["ignore-without-code"]

[tool.poetry.group.dev.dependencies]
mypy = "*"
nox = "*"
pyright = "*"
pytest = "*"
ruff = "*"

[tool.ruff]
line-length = 79
target-version = "py312"
unsafe-fixes = true

[tool.ruff.lint]
select = [
  "D", # pydocstyle
  "E", # pycodestyle
  "F", # pyflakes
  "I", # isort
]
ignore = [
  "D206", # indent-with-spaces
  "D300", # triple-single-quotes
  "E111", # indentation-with-invalid-multiple
  "E114", # indentation-with-invalid-multiple-comment
  "E117", # over-indented
  "E501", # line-too-long
]

[tool.ruff.pydocstyle]
convention = "pep257"
