[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
enable_error_code = ["ignore-without-code"]

[tool.poetry.group.dev.dependencies]
docformatter = "*"
mypy = "*"
pyright = "*"
ruff = "*"
toml-sort = "*"

[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = [
  "E501" # line-too-long
]
